In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import joblib

In [2]:
pip install PyQt5

Requirement already satisfied: PyQt5 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (5.15.11)
Requirement already satisfied: PyQt5-sip<13,>=12.15 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from PyQt5) (12.15.0)
Requirement already satisfied: PyQt5-Qt5<5.16.0,>=5.15.2 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from PyQt5) (5.15.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages)

In [3]:
pip install PySide2

Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F7AC972480>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pyside2/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F7ACBFEF60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pyside2/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F7ACBFED80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pyside2/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F7ACBFF4D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pyside2/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F7ACBFF860>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pyside2/
ERROR: Could not find a version that satisfies the requirement PySide2 (from versions: none)
ERROR: No matching distribution found for PySide2

In [4]:
import PyQt5

In [5]:
pip install streamlit

Requirement already satisfied: streamlit in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (1.39.0)
Requirement already satisfied: altair<6,>=4.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (5.4.1)
Requirement already satisfied: blinker<2,>=1.0.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (1.7.0)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: click<9,>=7.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (8.1.7)
Requirement already satisfied: numpy<3,>=1.20 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<11,>=7.1.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (10.4.0)
Requirement already satisfied: protobuf<6,>=3.20 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (5.28.3)
Requirement already satisfied: pyarrow>=7.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (17.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (13.9.3)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (4.12.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (3.1.43)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (0.9.1)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (6.4.1)
Requirement already satisfied: watchdog<6,>=2.1.5 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (5.0.3)
Requirement already satisfied: jinja2 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.3)
Requirement already satisfied: jsonschema>=3.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.5.2 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from altair<6,>=4.0->streamlit) (1.10.0)
Requirement already satisfied: colorama in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.11)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (2024.8.30)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from rich<14,>=10.14.0->streamlit) (2.18.0)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.5)
Requirement already satisfied: attrs>=22.2.0 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (24.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)
Requirement already satisfied: six>=1.5 in c:\users\welcome\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages)

In [6]:
import streamlit as st

In [7]:
bang=pd.read_csv("1 data_bangalore.csv")
bang['city']="Bangalore"
bang

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type.2,No Door Numbers.2,Cargo Volumn,Alloy Wheel Size.2,city
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,Bangalore
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,5.3 metres,Ventilated Disc,Drum,NaN,NaN,"Tubeless,Radial",4.0,352-litres,16,Bangalore
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,4.9 meters,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5.0,242-litres,14,Bangalore
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,4.7 metres,Disc,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4.0,407-litres,14,Bangalore
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,5.2 meters,Ventilated Disc,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5.0,353-litres,16,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1476,0,Diesel,SUV,"1,56,039",Manual,2,2nd Owner,Toyota,Toyota Fortuner,2012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore
1477,0,Petrol,Sedan,"56,000",Manual,2,2nd Owner,Maruti,Maruti SX4,2008,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore
1478,0,Petrol,Hatchback,"42,000",Manual,2,2nd Owner,Honda,Honda Brio,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore
1479,0,Diesel,Hatchback,"93,003",Manual,1,1st Owner,Hyundai,Hyundai i20,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore
1480,0,Petrol,Hatchback,"36,000",Automatic,2,2nd Owner,Hyundai,Hyundai Grand i10,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bangalore

In [8]:
bang.shape

(1481, 79)

In [9]:
chen=pd.read_csv("2 data_chennai.csv")
chen["city"]="chennai"
chen

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type.1,Alloy Wheel Size.1,No Door Numbers.1,Cargo Volumn,Acceleration,Top Speed,city
0,0,Petrol,Sedan,"70,000",Automatic,3,3rd Owner,Toyota,Toyota Camry,2014,...,5.5 metres,Ventilated Disc,Solid Disc,"Tubeless,Radial",17,4.0,NaN,NaN,NaN,chennai
1,0,Petrol,Hatchback,"23,981",Manual,1,1st Owner,Datsun,Datsun RediGO,2017,...,4.7m,Disc,Drum,NaN,NaN,5.0,222,NaN,NaN,chennai
2,0,Petrol,SUV,"7,100",Automatic,1,1st Owner,Renault,Renault Kiger,2021,...,NaN,Disc,Drum,"Tubeless, Radial",NaN,5.0,405,NaN,NaN,chennai
3,0,Petrol,Hatchback,"71,574",Manual,2,2nd Owner,Hyundai,Hyundai i20,2011,...,5.20 m,Disc,Drum,"Tubeless,Radial",14,5.0,295 Lit,12.96 Sec,NaN,chennai
4,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Audi,Audi Q3,2014,...,5.9 metres,Ventilated Disc,Drum,"Tubeless,Radial",16,5.0,460-litres,8.2 Seconds,212 Kmph,chennai
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,5.2 metres,Disc,Drum,"Tubeless,Radial",16,5.0,410-litres,14.20 Seconds,168 Kmph,chennai
1377,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chennai
1378,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chennai
1379,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chennai
1380,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chennai

In [10]:
bang_chen=pd.concat([bang,chen],axis=0).reset_index(drop=True)
bang_chen

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type.2,No Door Numbers.2,Cargo Volumn,Alloy Wheel Size.2,city
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,Bangalore
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,5.3 metres,Ventilated Disc,Drum,NaN,NaN,"Tubeless,Radial",4.0,352-litres,16,Bangalore
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,4.9 meters,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5.0,242-litres,14,Bangalore
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,4.7 metres,Disc,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4.0,407-litres,14,Bangalore
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,5.2 meters,Ventilated Disc,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5.0,353-litres,16,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2857,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,5.2 metres,Disc,Drum,168 Kmph,14.20 Seconds,NaN,NaN,410-litres,NaN,chennai
2858,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chennai
2859,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chennai
2860,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chennai
2861,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chennai

In [11]:
delhi=pd.read_csv("3 data_delhi.csv")
delhi["city"]="delhi"
delhi.head().shape

(5, 81)

In [12]:
bang_chen_delhi=pd.concat([bang_chen,delhi],axis=0).reset_index(drop=True)
bang_chen_delhi.shape

(4347, 86)

In [13]:
hyder=pd.read_csv("4 data_hyderabad.csv")
hyder["city"]="hyderabad"
hyder

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type.2,Alloy Wheel Size.2,No Door Numbers.2,Cargo Volumn,Top Speed,Acceleration,city
0,0,Petrol,Hatchback,"20,000",Automatic,1,1st Owner,Volkswagen,Volkswagen Polo,2022,...,4.9,Disc,Drum,"Tubeless,Radial",R16,5.0,280,NaN,NaN,hyderabad
1,0,Petrol,Hatchback,"85,582",Manual,2,2nd Owner,Hyundai,Hyundai EON,2014,...,4.6 metres,Disc,Drum,Tubeless,NaN,5.0,215-litres,135 Kmph,19 Seconds,hyderabad
2,0,Petrol,SUV,"10,000",Manual,1,1st Owner,Hyundai,Hyundai Venue,2023,...,NaN,Disc,Drum,"Tubeless, Radial",NaN,5.0,NaN,NaN,NaN,hyderabad
3,0,Petrol,Hatchback,"50,750",Manual,1,1st Owner,Maruti,Maruti Baleno,2017,...,4.9 meters,Disc,Drum,"Tubeless,Radial",16,5.0,339-litres,180 Kmph,12.36 seconds,hyderabad
4,0,Petrol,SUV,"10,000",Automatic,1,1st Owner,Mahindra,Mahindra Thar,2022,...,NaN,Disc,Drum,"Radial, Tubeless",18,3.0,NaN,NaN,NaN,hyderabad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1478,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Mahindra,Mahindra XUV500,2013,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hyderabad
1479,0,Diesel,Sedan,"50,000",Automatic,1,1st Owner,Jaguar,Jaguar XF,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hyderabad
1480,0,Diesel,Sedan,"1,20,000",Automatic,3,3rd Owner,BMW,BMW 5 Series,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hyderabad
1481,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Tata,Tata Nexon,2019,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hyderabad
1482,0,Diesel,MUV,"1,00,000",Manual,1,1st Owner,Toyota,Toyota Innova,2015,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,hyderabad

In [14]:
hyderabad=pd.concat([bang_chen_delhi,hyder],axis=0).reset_index(drop=True)
hyderabad

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Cargo Volumn,Alloy Wheel Size.2,city,Gear Box.1,Drive Type.1,Front Brake Type.1,Rear Brake Type.1,Turning Radius.1,Top Speed.1,Acceleration.1
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,235-litres,NaN,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,352-litres,16,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,242-litres,14,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,407-litres,14,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,353-litres,16,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5825,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Mahindra,Mahindra XUV500,2013,...,NaN,NaN,hyderabad,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5826,0,Diesel,Sedan,"50,000",Automatic,1,1st Owner,Jaguar,Jaguar XF,2014,...,NaN,NaN,hyderabad,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5827,0,Diesel,Sedan,"1,20,000",Automatic,3,3rd Owner,BMW,BMW 5 Series,2018,...,NaN,NaN,hyderabad,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5828,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Tata,Tata Nexon,2019,...,NaN,NaN,hyderabad,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5829,0,Diesel,MUV,"1,00,000",Manual,1,1st Owner,Toyota,Toyota Innova,2015,...,NaN,NaN,hyderabad,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
jai=pd.read_csv("5 data_jaipur.csv")
jai["city"]="jaipur"
jai

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius.1,Front Brake Type.1,Rear Brake Type.1,Top Speed.1,Acceleration.1,Tyre Type.1,Alloy Wheel Size.1,No Door Numbers.1,Cargo Volumn,city
0,0,Diesel,Hatchback,"1,20,000",Manual,2,2nd Owner,Hyundai,Hyundai i20,2015,...,5.2 metres,Disc,Drum,180 Kmph,11.9 Seconds,Tubeless,16,5.0,295-litres,jaipur
1,0,Petrol,Hatchback,"66,951",Manual,1,1st Owner,Maruti,Maruti Swift,2012,...,4.8,Disc,Drum,NaN,NaN,"Radial, Tubeless",NaN,5.0,268,jaipur
2,0,Petrol,Hatchback,"80,000",Automatic,2,2nd Owner,Maruti,Maruti Celerio,2016,...,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",NaN,5.0,235-litres,jaipur
3,0,Petrol,Hatchback,"44,392",Manual,1,1st Owner,Hyundai,Hyundai Grand i10,2017,...,4.8 metres,Disc,Drum,165 Kmph,12.9 Seconds,Tubeless,NaN,5.0,256,jaipur
4,0,Petrol,Hatchback,"40,000",Automatic,1,1st Owner,Maruti,Maruti Wagon R,2016,...,4.6 metres,Ventilated Disc,Drum,152 kmph,18.6 Seconds,Tubeless Tyres,NaN,5.0,180-liters,jaipur
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Chevrolet,Chevrolet Beat,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,jaipur
1116,0,Petrol,Hatchback,"70,000",Manual,1,1st Owner,Maruti,Maruti Alto,2007,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,jaipur
1117,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Renault,Renault Kiger,2022,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,jaipur
1118,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Alto,2009,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,jaipur
1119,0,Petrol,Hatchback,"80,000",Manual,1,1st Owner,Maruti,Maruti Baleno,2018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,jaipur

In [16]:
jaipur=pd.concat([hyderabad,jai],axis=0).reset_index(drop=True)
jaipur

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Cargo Volumn,Alloy Wheel Size.2,city,Gear Box.1,Drive Type.1,Front Brake Type.1,Rear Brake Type.1,Turning Radius.1,Top Speed.1,Acceleration.1
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,235-litres,NaN,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,352-litres,16,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,242-litres,14,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,407-litres,14,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,353-litres,16,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6945,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Chevrolet,Chevrolet Beat,2011,...,NaN,NaN,jaipur,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6946,0,Petrol,Hatchback,"70,000",Manual,1,1st Owner,Maruti,Maruti Alto,2007,...,NaN,NaN,jaipur,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6947,0,Petrol,SUV,"20,000",Manual,1,1st Owner,Renault,Renault Kiger,2022,...,NaN,NaN,jaipur,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6948,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Alto,2009,...,NaN,NaN,jaipur,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6949,0,Petrol,Hatchback,"80,000",Manual,1,1st Owner,Maruti,Maruti Baleno,2018,...,NaN,NaN,jaipur,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
kol=pd.read_csv("6 data_kolkata.csv")
kol["city"]='kolkata'
kol

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type.1,Alloy Wheel Size.1,No Door Numbers.1,Cargo Volumn,Acceleration,Top Speed,city
0,0,Petrol,Sedan,"70,000",Automatic,3,3rd Owner,Toyota,Toyota Camry,2014,...,5.5 metres,Ventilated Disc,Solid Disc,"Tubeless,Radial",17,4.0,NaN,NaN,NaN,kolkata
1,0,Petrol,Hatchback,"23,981",Manual,1,1st Owner,Datsun,Datsun RediGO,2017,...,4.7m,Disc,Drum,NaN,NaN,5.0,222,NaN,NaN,kolkata
2,0,Petrol,SUV,"7,100",Automatic,1,1st Owner,Renault,Renault Kiger,2021,...,NaN,Disc,Drum,"Tubeless, Radial",NaN,5.0,405,NaN,NaN,kolkata
3,0,Petrol,Hatchback,"71,574",Manual,2,2nd Owner,Hyundai,Hyundai i20,2011,...,5.20 m,Disc,Drum,"Tubeless,Radial",14,5.0,295 Lit,12.96 Sec,NaN,kolkata
4,0,Diesel,SUV,"50,000",Automatic,2,2nd Owner,Audi,Audi Q3,2014,...,5.9 metres,Ventilated Disc,Drum,"Tubeless,Radial",16,5.0,460-litres,8.2 Seconds,212 Kmph,kolkata
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,5.2 metres,Disc,Drum,"Tubeless,Radial",16,5.0,410-litres,14.20 Seconds,168 Kmph,kolkata
1377,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kolkata
1378,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kolkata
1379,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kolkata
1380,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kolkata

In [18]:
df=pd.concat([jaipur,kol],axis=0).reset_index(drop=True)
df

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Cargo Volumn,Alloy Wheel Size.2,city,Gear Box.1,Drive Type.1,Front Brake Type.1,Rear Brake Type.1,Turning Radius.1,Top Speed.1,Acceleration.1
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,235-litres,NaN,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,352-litres,16,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,242-litres,14,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,407-litres,14,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,353-litres,16,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8326,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,410-litres,NaN,kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8327,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,NaN,NaN,kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8328,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,NaN,NaN,kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8329,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,NaN,NaN,kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8330,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,NaN,NaN,kolkata,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8331 entries, 0 to 8330
Data columns (total 86 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   it                        8331 non-null   int64
 1   ft                        8331 non-null   object
 2   bt                        8326 non-null   object
 3   km                        8331 non-null   object
 4   transmission              8331 non-null   object
 5   ownerNo                   8331 non-null   int64
 6   owner                     8331 non-null   object
 7   oem                       8331 non-null   object
 8   model                     8331 non-null   object
 9   modelYear                 8331 non-null   int64
 10  centralVariantId          8331 non-null   int64
 11  variantName               8331 non-null   object
 12  price                     8331 non-null   object
 13  priceActual               1522 non-null   object
 14  priceSaving               0 non-null      float64
 15  priceFixedText            0 non-null      float64
 16  trendingText              8331 non-null   object
 17  Registration Year         8296 non-null   object
 18  Insurance Validity        8327 non-null   object
 19  Fuel Type                 8331 non-null   object
 20  Seats                     8322 non-null   object
 21  Kms Driven                8329 non-null   object
 22  RTO                       7363 non-null   object
 23  Ownership                 8317 non-null   object
 24  Engine Displacement       8327 non-null   object
 25  Transmission              8331 non-null   object
 26  Year of Manufacture       8310 non-null   float64
 27  Mileage                   8041 non-null   object
 28  Engine                    8327 non-null   object
 29  Max Power                 8272 non-null   object
 30  Torque                    8272 non-null   object
 31  Seats.1                   8322 non-null   float64
 32  Wheel Size                5272 non-null   object
 33  Color                     8328 non-null   object
 34  Engine Type               8031 non-null   object
 35  Displacement              8327 non-null   float64
 36  Max Power.1               8272 non-null   object
 37  Max Torque                8272 non-null   object
 38  No of Cylinder            8295 non-null   float64
 39  Values per Cylinder       8275 non-null   float64
 40  Value Configuration       6073 non-null   object
 41  Fuel Suppy System         6582 non-null   object
 42  BoreX Stroke              2362 non-null   object
 43  Compression Ratio         1888 non-null   object
 44  Turbo Charger             7258 non-null   object
 45  Super Charger             6341 non-null   object
 46  Seating Capacity          16 non-null     float64
 47  Steering Type             16 non-null     object
 48  Tyre Type                 16 non-null     object
 49  Alloy Wheel Size          15 non-null     float64
 50  No Door Numbers           16 non-null     float64
 51  Length                    8254 non-null   object
 52  Width                     8251 non-null   object
 53  Height                    8254 non-null   object
 54  Wheel Base                8179 non-null   object
 55  Front Tread               4823 non-null   object
 56  Rear Tread                4817 non-null   object
 57  Kerb Weight               8279 non-null   object
 58  Gross Weight              3839 non-null   object
 59  Ground Clearance Unladen  502 non-null    object
 60  Seating Capacity.1        5360 non-null   float64
 61  Steering Type.1           5167 non-null   object
 62  Tyre Type.1               5312 non-null   object
 63  Alloy Wheel Size.1        3331 non-null   object
 64  No Door Numbers.1         5355 non-null   float64
 65  Gear Box                  5651 non-null   object
 66  Drive Type                4582 non-null   object
 67  Seating Capacity.2        2946 non-null   float64
 68  Steering Type.2           2864 non-null   object
 69  Turning Radius            4646 non-null   object
 70  Front Brake Type          5666 non-null   object
 71  Rear Brake Type           5666 non-null   object
 72  Top Speed                 3059 non-null   object
 73  Acceleration              3239 non-null   object
 74  Tyre Type.2               2924 non-null   object
 75  No Door Numbers.2         2945 non-null   float64
 76  Cargo Volumn              6670 non-null   object
 77  Alloy Wheel Size.2        1926 non-null   object
 78  city                      8331 non-null   object
 79  Gear Box.1                2574 non-null   object
 80  Drive Type.1              2154 non-null   object
 81  Front Brake Type.1        2573 non-null   object
 82  Rear Brake Type.1         2573 non-null   object
 83  Turning Radius.1          2092 non-null   object
 84  Top Speed.1               1469 non-null   object
 85  Acceleration.1            1547 non-null   object
dtypes: float64(14), int64(4), object(68)
memory usage: 5.5+ MB

In [20]:
kolkata=df.drop(df.columns[df.isnull().mean()>0.50],axis=1)
kolkata.isnull().sum()/len(kolkata)*100

it                      0.000000
ft                      0.000000
bt                      0.060017
km                      0.000000
transmission            0.000000
ownerNo                 0.000000
owner                   0.000000
oem                     0.000000
model                   0.000000
modelYear               0.000000
centralVariantId        0.000000
variantName             0.000000
price                   0.000000
trendingText            0.000000
Registration Year       0.420118
Insurance Validity      0.048013
Fuel Type               0.000000
Seats                   0.108030
Kms Driven              0.024007
RTO                    11.619253
Ownership               0.168047
Engine Displacement     0.048013
Transmission            0.000000
Year of Manufacture     0.252071
Mileage                 3.480975
Engine                  0.048013
Max Power               0.708198
Torque                  0.708198
Seats.1                 0.108030
Wheel Size             36.718281
Color                   0.036010
Engine Type             3.601008
Displacement            0.048013
Max Power.1             0.708198
Max Torque              0.708198
No of Cylinder          0.432121
Values per Cylinder     0.672188
Value Configuration    27.103589
Fuel Suppy System      20.993878
Turbo Charger          12.879606
Super Charger          23.886688
Length                  0.924259
Width                   0.960269
Height                  0.924259
Wheel Base              1.824511
Front Tread            42.107790
Rear Tread             42.179810
Kerb Weight             0.624175
Seating Capacity.1     35.661985
Steering Type.1        37.978634
Tyre Type.1            36.238147
No Door Numbers.1      35.722002
Gear Box               32.169007
Drive Type             45.000600
Turning Radius         44.232385
Front Brake Type       31.988957
Rear Brake Type        31.988957
Cargo Volumn           19.937583
city                    0.000000
dtype: float64

In [21]:
kolkata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8331 entries, 0 to 8330
Data columns (total 59 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   it                   8331 non-null   int64
 1   ft                   8331 non-null   object
 2   bt                   8326 non-null   object
 3   km                   8331 non-null   object
 4   transmission         8331 non-null   object
 5   ownerNo              8331 non-null   int64
 6   owner                8331 non-null   object
 7   oem                  8331 non-null   object
 8   model                8331 non-null   object
 9   modelYear            8331 non-null   int64
 10  centralVariantId     8331 non-null   int64
 11  variantName          8331 non-null   object
 12  price                8331 non-null   object
 13  trendingText         8331 non-null   object
 14  Registration Year    8296 non-null   object
 15  Insurance Validity   8327 non-null   object
 16  Fuel Type            8331 non-null   object
 17  Seats                8322 non-null   object
 18  Kms Driven           8329 non-null   object
 19  RTO                  7363 non-null   object
 20  Ownership            8317 non-null   object
 21  Engine Displacement  8327 non-null   object
 22  Transmission         8331 non-null   object
 23  Year of Manufacture  8310 non-null   float64
 24  Mileage              8041 non-null   object
 25  Engine               8327 non-null   object
 26  Max Power            8272 non-null   object
 27  Torque               8272 non-null   object
 28  Seats.1              8322 non-null   float64
 29  Wheel Size           5272 non-null   object
 30  Color                8328 non-null   object
 31  Engine Type          8031 non-null   object
 32  Displacement         8327 non-null   float64
 33  Max Power.1          8272 non-null   object
 34  Max Torque           8272 non-null   object
 35  No of Cylinder       8295 non-null   float64
 36  Values per Cylinder  8275 non-null   float64
 37  Value Configuration  6073 non-null   object
 38  Fuel Suppy System    6582 non-null   object
 39  Turbo Charger        7258 non-null   object
 40  Super Charger        6341 non-null   object
 41  Length               8254 non-null   object
 42  Width                8251 non-null   object
 43  Height               8254 non-null   object
 44  Wheel Base           8179 non-null   object
 45  Front Tread          4823 non-null   object
 46  Rear Tread           4817 non-null   object
 47  Kerb Weight          8279 non-null   object
 48  Seating Capacity.1   5360 non-null   float64
 49  Steering Type.1      5167 non-null   object
 50  Tyre Type.1          5312 non-null   object
 51  No Door Numbers.1    5355 non-null   float64
 52  Gear Box             5651 non-null   object
 53  Drive Type           4582 non-null   object
 54  Turning Radius       4646 non-null   object
 55  Front Brake Type     5666 non-null   object
 56  Rear Brake Type      5666 non-null   object
 57  Cargo Volumn         6670 non-null   object
 58  city                 8331 non-null   object
dtypes: float64(7), int64(4), object(48)
memory usage: 3.8+ MB

In [22]:
# DATA CLEANING AND PREPROCESSING

In [23]:
kolkata['it']=kolkata['it'].fillna(0)

In [24]:
kolkata=kolkata.drop(columns=["it"])

In [25]:
kolkata=kolkata.drop(columns=["ft"])

In [26]:

#fuel=LabelEncoder()
#kolkata["FuelType"]=fuel.fit_transform(kolkata["Fuel Type"])

In [27]:
print(kolkata["Fuel Type"].unique())

['Petrol' 'Diesel' 'LPG' 'CNG' 'Electric']

In [28]:
print(kolkata["bt"].unique())

['Hatchback' 'SUV' 'Sedan' 'MUV' 'Coupe' 'Minivans' 'Pickup Trucks'
 'Convertibles' nan 'Wagon']

In [29]:
btt=kolkata["bt"].mode()[0]
kolkata["bt"]=kolkata["bt"].fillna(btt)

In [30]:
#label_encoder= LabelEncoder()
#kolkata["bt_encoded"]=label_encoder.fit_transform(kolkata['bt'])
#tran=LabelEncoder()
#kolkata['transmission']=tran.fit_transform(kolkata['transmission'])

In [31]:
#kolkata=kolkata.drop(columns=["bt"])

In [32]:
kolkata["km"]= kolkata["km"].str.replace(',', '').astype(int)

In [33]:
#kolkata = pd.get_dummies(kolkata, columns=['transmission'],dtype=int)

In [34]:
#kolkata["Manual_transmission"]=kolkata["Transmission"].apply([lambda x:1 if x=="Petrol" else 0])
#kolkata["Automatic_transmission"]=kolkata["Transmission"].apply([lambda x:1 if x=="Diesel" else 0])

In [35]:
kolkata

,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,...,Steering Type.1,Tyre Type.1,No Door Numbers.1,Gear Box,Drive Type,Turning Radius,Front Brake Type,Rear Brake Type,Cargo Volumn,city
0,Hatchback,120000,Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,3979,VXI,...,NaN,NaN,NaN,5 Speed,FWD,4.7 metres,Ventilated Disc,Drum,235-litres,Bangalore
1,SUV,32706,Manual,2,2nd Owner,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,...,NaN,NaN,NaN,5 Speed,FWD,5.3 metres,Ventilated Disc,Drum,352-litres,Bangalore
2,Hatchback,11949,Manual,1,1st Owner,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,...,NaN,NaN,NaN,5 Speed,FWD,4.9 meters,Disc,Drum,242-litres,Bangalore
3,Sedan,17794,Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,...,NaN,NaN,NaN,5 Speed,FWD,4.7 metres,Disc,Drum,407-litres,Bangalore
4,SUV,60000,Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,4277,DDiS 200 Zeta,...,NaN,NaN,NaN,5 Speed,FWD,5.2 meters,Ventilated Disc,Solid Disc,353-litres,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8326,Hatchback,10000,Manual,1,1st Owner,Maruti,Maruti Celerio,2022,8682,ZXI BSVI,...,Power,"Tubeless,Radial",5.0,6 Speed,AWD,5.2 metres,Disc,Drum,410-litres,kolkata
8327,Hatchback,120000,Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,3943,LXI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kolkata
8328,Sedan,50000,Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,4672,C 200 CGI Elegance,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kolkata
8329,Hatchback,40000,Manual,1,1st Owner,Maruti,Maruti Ritz,2012,4144,ZXi,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kolkata
8330,SUV,120000,Manual,2,2nd Owner,Renault,Renault Duster,2017,5048,110PS Diesel RxZ AWD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kolkata

In [36]:
kolkata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8331 entries, 0 to 8330
Data columns (total 57 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   bt                   8331 non-null   object
 1   km                   8331 non-null   int32
 2   transmission         8331 non-null   object
 3   ownerNo              8331 non-null   int64
 4   owner                8331 non-null   object
 5   oem                  8331 non-null   object
 6   model                8331 non-null   object
 7   modelYear            8331 non-null   int64
 8   centralVariantId     8331 non-null   int64
 9   variantName          8331 non-null   object
 10  price                8331 non-null   object
 11  trendingText         8331 non-null   object
 12  Registration Year    8296 non-null   object
 13  Insurance Validity   8327 non-null   object
 14  Fuel Type            8331 non-null   object
 15  Seats                8322 non-null   object
 16  Kms Driven           8329 non-null   object
 17  RTO                  7363 non-null   object
 18  Ownership            8317 non-null   object
 19  Engine Displacement  8327 non-null   object
 20  Transmission         8331 non-null   object
 21  Year of Manufacture  8310 non-null   float64
 22  Mileage              8041 non-null   object
 23  Engine               8327 non-null   object
 24  Max Power            8272 non-null   object
 25  Torque               8272 non-null   object
 26  Seats.1              8322 non-null   float64
 27  Wheel Size           5272 non-null   object
 28  Color                8328 non-null   object
 29  Engine Type          8031 non-null   object
 30  Displacement         8327 non-null   float64
 31  Max Power.1          8272 non-null   object
 32  Max Torque           8272 non-null   object
 33  No of Cylinder       8295 non-null   float64
 34  Values per Cylinder  8275 non-null   float64
 35  Value Configuration  6073 non-null   object
 36  Fuel Suppy System    6582 non-null   object
 37  Turbo Charger        7258 non-null   object
 38  Super Charger        6341 non-null   object
 39  Length               8254 non-null   object
 40  Width                8251 non-null   object
 41  Height               8254 non-null   object
 42  Wheel Base           8179 non-null   object
 43  Front Tread          4823 non-null   object
 44  Rear Tread           4817 non-null   object
 45  Kerb Weight          8279 non-null   object
 46  Seating Capacity.1   5360 non-null   float64
 47  Steering Type.1      5167 non-null   object
 48  Tyre Type.1          5312 non-null   object
 49  No Door Numbers.1    5355 non-null   float64
 50  Gear Box             5651 non-null   object
 51  Drive Type           4582 non-null   object
 52  Turning Radius       4646 non-null   object
 53  Front Brake Type     5666 non-null   object
 54  Rear Brake Type      5666 non-null   object
 55  Cargo Volumn         6670 non-null   object
 56  city                 8331 non-null   object
dtypes: float64(7), int32(1), int64(3), object(46)
memory usage: 3.6+ MB

In [37]:
kolkata=kolkata.drop(columns=["Transmission"])

In [ ]:
print(kolkata["oem"].unique())
label_encoder1=LabelEncoder()
kolkata["car_names_encoded"]=label_encoder1.fit_transform(kolkata["oem"])
kolkata["car_names_encoded"]

['Maruti' 'Ford' 'Tata' 'Hyundai' 'Jeep' 'Datsun' 'Honda' 'Mahindra'
 'Mercedes-Benz' 'BMW' 'Renault' 'Audi' 'Toyota' 'Mini' 'Kia' 'Skoda'
 'Volkswagen' 'Volvo' 'MG' 'Nissan' 'Fiat' 'Mahindra Ssangyong'
 'Mitsubishi' 'Jaguar' 'Land Rover' 'Chevrolet' 'Citroen' 'Opel'
 'Mahindra Renault' 'Hindustan Motors' 'Porsche' 'Isuzu' 'Lexus']

0       20
1        6
2       29
3        9
4       20
        ..
8326    20
8327    20
8328    21
8329    20
8330    27
Name: car_names_encoded, Length: 8331, dtype: int32

In [39]:
kolkata=kolkata.drop(columns=["oem"])

In [40]:
print(kolkata["model"].unique())
label_encoder1=LabelEncoder()
kolkata["Model_encoded"]=label_encoder1.fit_transform(kolkata["model"])
kolkata["Model_encoded"].info()

['Maruti Celerio' 'Ford Ecosport' 'Tata Tiago' 'Hyundai Xcent'
 'Maruti SX4 S Cross' 'Jeep Compass' 'Datsun GO' 'Hyundai Venue'
 'Maruti Ciaz' 'Maruti Baleno' 'Hyundai Grand i10' 'Honda Jazz'
 'Mahindra XUV500' 'Mercedes-Benz GLA' 'Hyundai i20' 'Tata Nexon'
 'Honda City' 'BMW 5 Series' 'Maruti Swift' 'Renault Duster'
 'Mercedes-Benz S-Class' 'Hyundai Santro' 'Hyundai Santro Xing'
 'Mercedes-Benz E-Class' 'Audi A4' 'Maruti Wagon R' 'Maruti Ertiga'
 'Mercedes-Benz C-Class' 'Toyota Fortuner' 'Hyundai Elantra' 'Audi A6'
 'Maruti Alto 800' 'Mahindra Scorpio' 'Mini 3 DOOR' 'Kia Seltos'
 'Maruti Alto' 'Mercedes-Benz GL-Class' 'Tata New Safari' 'Audi Q7'
 'Renault KWID' 'Hyundai Getz' 'Skoda Rapid' 'Hyundai Creta'
 'Tata Harrier' 'BMW 3 Series GT' 'Renault Lodgy' 'Skoda Octavia'
 'Maruti Ritz' 'Volkswagen Polo' 'Mahindra KUV 100' 'BMW X3' 'Hyundai i10'
 'Volvo S60' 'Mahindra XUV300' 'MG Hector Plus' 'Honda Brio'
 'Maruti Alto K10' 'Renault Kiger' 'Hyundai EON' 'Volkswagen Vento'
 'Toyota Yaris' 'MG Hector' 'Hyundai Alcazar' 'Volkswagen T-Roc'
 'BMW 3 Series' 'Skoda Superb' 'Audi Q5' 'Ford Endeavour' 'Ford Figo'
 'Maruti Ignis' 'Renault Triber' 'BMW X5' 'Hyundai Tucson' 'Hyundai Verna'
 'Mercedes-Benz GLC' 'Nissan Terrano' 'Honda CR-V'
 'Mercedes-Benz A-Class Limousine' 'Toyota Innova' 'Hyundai Santa Fe'
 'BMW 6 Series' 'Maruti Baleno RS' 'Renault Captur' 'Maruti Vitara Brezza'
 'Maruti Swift Dzire' 'Fiat Linea' 'Hyundai i20 Active' 'Honda WR-V'
 'Mahindra Ssangyong Rexton' 'Toyota Corolla Altis' 'Ford Ikon'
 'Mitsubishi Cedia' 'Jaguar XF' 'Audi A3' 'Skoda Kushaq'
 'Volkswagen Taigun' 'MG Astor' 'Hyundai Accent' 'Mercedes-Benz B Class'
 'Kia Carnival' 'Skoda Laura' 'BMW X4' 'Mini Cooper'
 'Land Rover Discovery Sport' 'Volvo XC40' 'Kia Sonet' 'Mahindra Verito'
 'Maruti S-Presso' 'Volkswagen Jetta' 'Datsun RediGO' 'Ford Aspire'
 'Ford Freestyle' 'Audi Q3' 'Tata Tigor' 'Jaguar F-Pace'
 'Mercedes-Benz A Class' 'Toyota Glanza' 'Nissan Magnite' 'Maruti Gypsy'
 'Tata Safari Storme' 'Maruti Celerio X' 'Mercedes-Benz M-Class'
 'Mercedes-Benz GLE' 'Toyota Urban cruiser' 'Mahindra Thar'
 'Mercedes-Benz CLA' 'Mahindra e2o Plus' 'MG Comet EV' 'Maruti Omni'
 'Volkswagen Tiguan' 'Tata Altroz' 'Tata Nexon EV Max' 'Tata Indica V2'
 'Toyota Innova Crysta' 'Volkswagen Ameo' 'Tata Nexon EV Prime' 'BMW X1'
 'Chevrolet Cruze' 'Toyota Camry' 'Fiat Punto Abarth' 'Mahindra TUV 300'
 'Chevrolet Beat' 'Maruti Eeco' 'Maruti 1000' 'Citroen C5 Aircross'
 'Mahindra XUV700' 'Hyundai Grand i10 Nios' 'Maruti Zen' 'Mahindra Quanto'
 'Land Rover Freelander 2' 'OpelCorsa' 'Mahindra Xylo' 'Tata Zest'
 'Honda New Accord' 'Skoda Yeti' 'Maruti SX4' 'Jaguar XE'
 'Chevrolet Spark' 'Hyundai i20 N Line' 'Chevrolet Tavera' 'BMW X7'
 'Mahindra Renault Logan' 'Citroen C3' 'Tata Nano' 'Honda Amaze'
 'Mahindra Bolero Power Plus' 'Tata Manza' 'Maruti Esteem' 'Tata Hexa'
 'Nissan Micra Active' 'Mitsubishi Lancer' 'Ford Fiesta'
 'Mahindra Bolero Camper' 'Fiat Punto' 'Kia Carens' 'Chevrolet Enjoy'
 'Volkswagen Tiguan Allspace' 'Skoda Slavia' 'Mahindra Marazzo'
 'Tata Indigo' 'Jaguar XJ' 'Skoda Fabia' 'Tata Sumo' 'Ford Mondeo'
 'Nissan Sunny' 'Fiat Palio' 'Toyota Etios' 'Maruti Estilo'
 'Mahindra Bolero' 'Jeep Meridian' 'BMW 1 Series' 'Volvo XC 90'
 'Audi A3 cabriolet' 'MG Gloster' 'Land Rover Range Rover Sport'
 'Nissan Micra' 'Fiat Punto EVO' 'Mini Cooper Countryman'
 'Renault Fluence' 'Land Rover Range Rover Evoque' 'Honda Civic'
 'Jeep Wrangler' 'Honda BR-V' 'Ambassador' 'Mahindra KUV 100 NXT'
 'Maruti Zen Estilo' 'Maruti A-Star' 'Volvo S60 Cross Country'
 'Volvo XC60' 'Jeep Compass Trailhawk' 'Land Rover Range Rover Velar'
 'Maruti Wagon R Stingray' 'Maruti XL6' 'Renault Scala' 'Tata Sumo Victa'
 'Porsche Macan' 'Chevrolet Sail' 'Toyota Etios Liva' 'Volvo V40'
 'Mercedes-Benz GLA Class' 'Porsche Panamera' 'Hyundai Sonata' 'Audi Q2'
 'Mercedes-Benz AMG GT' 'Mahindra Alturas G4' 'Maruti Brezza'
 'Tata Indica' 'BMW 3 Series Gran Limousine' 'Audi S5 Sportback'
 'Chevrolet Aveo' 'Renault Pulse' 'Tata Punch' 'Honda Mobilio'
 'Tata Tiago NRG' 'Mahindra Bolero Neo' 'Maruti Grand Vitara'
 'Hyundai Aura' 'Ford Fiesta Classic' 'Mahindra Scorpio N'
 'Toyota Etios Cross' 'Datsun GO Plus' 'Tata Nexon EV' 'Jaguar F-TYPE'
 'Tata Tigor EV' 'Toyota Fortuner Legender' 'Fiat Grande Punto'
 'Hyundai Xcent Prime' 'Maruti 800' 'Nissan Kicks' 'Mini Cooper SE'
 'BMW 7 Series' 'Isuzu MU-X' 'Mitsubishi Pajero' 'Land Rover Defender'
 'Mercedes-Benz GLC Coupe' 'Lexus RX' 'Mitsubishi Outlander'
 'Mercedes-Benz GLS' 'Mercedes-Benz CLS-Class' 'Maruti Jimny'
 'Mini Cooper Clubman' 'Land Rover Discovery' 'Mercedes-Benz AMG A 35'
 'Porsche Cayenne' 'Mercedes-Benz AMG G 63' 'Audi Q3 Sportback'
 'Maruti Swift Dzire Tour' 'Mercedes-Benz G' 'Mini Cooper Convertible'
 'Toyota Vellfire' 'Toyota Land Cruiser 300' 'Mahindra Scorpio Classic'
 'Volvo S90' 'Mercedes-Benz SLC' 'Isuzu D-Max' 'Chevrolet Optra'
 'Toyota Hyryder' 'Maruti FRONX' 'Maruti Celerio Tour 2018-2021'
 'Lexus ES' 'Mahindra Jeep' 'Toyota Qualis' 'Volkswagen Passat'
 'Volkswagen Virtus' 'Land Rover Range Rover' 'Fiat Avventura'
 'Honda City Hybrid' 'Tata Aria' 'Tata Bolt' 'MG ZS EV'
 'Mahindra E Verito' 'Mercedes-Benz EQC' 'Fiat Abarth Avventura'
 'Hindustan Motors Contessa' 'Tata Yodha Pickup' 'Tata Indigo Marina'
 'Chevrolet Captiva' 'Mahindra Bolero Pik Up Extra Long' 'Toyota Corolla'
 'Skoda Kodiaq' 'Mercedes-Benz AMG GLC 43' 'Chevrolet Aveo U-VA'
 'Hyundai Kona' 'Porsche 911' 'Volkswagen CrossPolo']
<class 'pandas.core.series.Series'>
RangeIndex: 8331 entries, 0 to 8330
Series name: Model_encoded
Non-Null Count  Dtype
--------------  -----
8331 non-null   int32
dtypes: int32(1)
memory usage: 32.7 KB

In [41]:
kolkata=kolkata.drop(columns=["model"])

In [42]:
kolkata["Gear Box"].unique()

array(['5 Speed ', '5 Speed', '6 Speed', '7-Speed', '4 Speed', '6 Speed ',
       '8G-DCT', '5-Speed', '7 Speed', '9 Speed', '8 Speed',
       '8-Speed Steptronic', '6-Speed', '7-Speed DCT', '9-Speed',
       '8 Speed Tiptronic', '5', '6 Speed IMT', '6-speed AutoSHIFT',
       '6-speed CVT', 'CVT', '6-speed', '7-speed DCT', '7 Speed DSG',
       '7 Speed DCT', '6', '8-Speed', '5-speed', '6 speed ',
       '8-Speed Steptronic Sport Automatic Transmission', '5 speed',
       '7 Speed CVT', 'Five Speed Manual', '5 Speed CVT', nan,
       '6 Speed AT', '6-Speed iMT', '6-Speed DCT', '7-Speed S-Tronic ',
       '7G DCT 7-Speed Dual Clutch Transmission ', '7-Speed S-Tronic',
       '5-Speed`', '9 speed Tronic', '6-Speed IVT', 'Direct Drive',
       '6 Speed IVT', 'IVT', '8 Speed CVT',
       'Five Speed Manual Transmission', '5 Speed AT+ Paddle Shifters',
       '8-Speed ', 'iMT', 'AGS', '6Speed', '4-Speed', '6-Speed IMT',
       '6 Speed MT', '9-speed automatic', '5 speed manual', '9 -speed',
       '8', '8 speed', '6-speed DCT', '8-speed', '7-speed Stronic',
       '7 Speed 7G-DCT', '4 Speed ', 'Mercedes Benz 7 Speed Automatic',
       '8 Speed Sport', '8-speed tiptronic', '7-Speed S tronic',
       '8-Speed Automatic Transmission', '9G TRONIC', 'eCVT',
       'Single Speed', '6 Speed with Sequential Shift', '8 Speed ',
       '6-speed IVT', 'Five Speed Manual Transmission Gearbox',
       'Six Speed Manual with Paddle Shifter', '6-Speed AT',
       '6-speed iMT', '7-Speed DSG', '7 speed', '6 speed automatic',
       '7G-DCT', 'Six Speed Geartronic, Six Speed Automati',
       '5 Speed Manual (Cable Type Gear Shift)',
       'Six Speed Automatic Gearbox', '10 Speed', 'Fully Automatic',
       'Single-speed transmission', 'Six Speed  Gearbox',
       '5 Speed Forward, 1 Reverse', '7 Speed S tronic'], dtype=object)

In [43]:
kolkata["variantName"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 8331 entries, 0 to 8330
Series name: variantName
Non-Null Count  Dtype
--------------  -----
8331 non-null   object
dtypes: object(1)
memory usage: 65.2+ KB

In [44]:
kolkata["variantName_encoded"]=label_encoder1.fit_transform(kolkata["variantName"])
kolkata["variantName_encoded"]

0       1635
1        266
2        122
3         95
4        896
        ...
8326    1865
8327    1150
8328     811
8329    1882
8330     420
Name: variantName_encoded, Length: 8331, dtype: int32

In [45]:
kolkata=kolkata.drop(columns=["variantName"])

In [46]:
print(kolkata['price'].unique())
def clean_price(price):

    price = price.replace('₹', '').replace(',', '').strip()
    if 'Lakh' in price:
        return float(price.replace('Lakh', '').strip()) * 1_00_000
    elif 'Thousand' in price:
        return float(price.replace('Thousand', '').strip()) * 1_000
    elif 'Crore' in price:
        return float(price.replace('Crore', '').strip()) * 1_00_00_000
    else:
        return float(price)
kolkata['price']=kolkata['price'].apply(clean_price)

['₹ 4 Lakh' '₹ 8.11 Lakh' '₹ 5.85 Lakh' ... '₹ 1.22 Lakh' '₹ 79,000 '
 '₹ 72,000 ']

In [47]:
kolkata['price'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 8331 entries, 0 to 8330
Series name: price
Non-Null Count  Dtype
--------------  -----
8331 non-null   float64
dtypes: float64(1)
memory usage: 65.2 KB

In [48]:
#p=kolkata['priceActual']
#def price(p):
 #   if isinstance(p, str):
  #      p = p.replace('₹', '').replace(',', '')
   #     if 'Lakh' in p:
    #        return float(p.replace('Lakh', '').strip()) * 1_00_000
     #   elif 'Thousand' in p:
      #      return float(p.replace('Thousand', '').strip()) * 1_000
       # elif 'Crore' in p:
        #    return float(p.replace('Crore', '').strip()) * 1_00_00_000
        #else:
        #    return float(p)
#kolkata['priceActual']=kolkata['priceActual'].apply(price(p))

In [49]:
print(kolkata["Registration Year"].unique())

['2015' 'Feb 2018' 'Sept 2018' 'Dec 2014' '2020' 'Aug 2017' '2021'
 'Aug 2018' 'Jan 2018' '2018' 'May 2019' 'Oct 2018' 'Aug 2014' 'Jun 2022'
 'May 2014' '2022' 'Sept 2016' '2011' 'Mar 2016' 'Jun 2016' '2016'
 'Nov 2018' '2009' 'Nov 2017' 'Apr 2014' 'Oct 2014' 'Oct 2021' 'May 2015'
 '2019' 'Jan 2019' 'Mar 2015' 'Oct 2020' 'May 2016' '2017' '2013'
 'Jul 2016' 'Dec 2021' '2010' 'Jul 2019' 'Aug 2020' 'Dec 2018' 'Jul 2022'
 '2008' 'Aug 2019' '2014' 'Jul 2021' 'Jul 2015' '2006' 'Feb 2019'
 'Aug 2021' 'Jun 2017' 'Apr 2021' 'Jul 2014' 'Nov 2016' 'Jul 2018'
 'Jan 2013' 'Aug 2013' 'Feb 2014' 'Dec 2016' 'Jun 2013' 'Mar 2019'
 'May 2018' 'Dec 2022' 'Mar 2010' 'Oct 2012' 'Jan 2016' '2012' 'Jul 2017'
 'May 2022' 'Nov 2011' 'Sept 2015' 'Nov 2020' 'Jan 2015' 'Oct 2022'
 'Sept 2017' 'Jan 2010' 'Oct 2017' 'Feb 2020' 'Jan 2012' 'Jun 2018'
 'Jun 2012' 'Oct 2015' 'Oct 2013' 'May 2017' 'Apr 2015' 'Feb 2015'
 'Mar 2014' 'Apr 2017' 'Mar 2018' 'Oct 2019' 'Apr 2016' 'Jun 2019'
 'Jan 2017' 'Mar 2020' '2005' 'Oct 2008' 'Jan 2021' 'May 2008' 'Dec 2012'
 'Apr 2018' 'Jun 2020' 'Feb 2017' '2007' 'Apr 2022' '2023' 'Mar 2013'
 'Dec 2017' 'Sept 2022' 'Jan 2014' 'Jun 2015' 'Sept 2019' 'Jul 2020'
 'Dec 2011' 'Feb 2013' 'Aug 2015' 'Aug 2016' 'May 2021' 'Jun 2011'
 'Nov 2013' 'Aug 2008' 'Feb 2021' 'Aug 2012' 'Mar 2021' 'Jun 2014'
 'Aug 2010' 'Nov 2019' 'Nov 2014' 'Sept 2020' 'Mar 2017' 'May 2020'
 'Oct 2016' 'Jun 2010' 'Dec 2020' 'Mar 2023' 'Jul 2011' 'Nov 2012'
 'Dec 2015' 'Mar 2022' nan 'Apr 2019' 'Jul 2013' 'Aug 2011' 'Nov 2021'
 'Feb 2022' 'Jun 2021' 'Feb 2011' 'Feb 2016' 'Nov 2022' '2004' 'Mar 2012'
 'Jan 2022' '2003' 'Nov 2015' 'Sept 2012' 'May 2012' 'Sept 2021'
 'Oct 2010' 'Dec 2010' 'Apr 2013' 'Apr 2020' 'May 2013' 'Oct 2011'
 'Sept 2013' 'Mar 2011' '2002' 'Mar 2008' 'Jan 2020' 'Jun 2023' 'Dec 2013'
 'Aug 2022' 'Apr 2010' 'Feb 2012' 'Dec 2019' 'Jan 2011' 'Feb 2023'
 'Sept 2014' 'Jul 2008' 'Sept 2009' 'Jun 2008' 'Apr 2011' 'May 2023'
 'Jan 2009' 'Jul 2023' 'Jul 2010' 'Sept 2011' 'Aug 2007' 'Sept 2010'
 'Aug 2023' 'Jul 2012' 'Apr 2012' 'May 2011' 'May 2010' 'Dec 2009'
 'Nov 2010' 'Dec 2003' 'Mar 2009' 'Jan 2023' 'Aug 2009' 'Apr 2023'
 'Sept 2023' 'Jun 2009' 'Jul 2003' 'Dec 2004' 'May 2009' 'Jul 2004'
 'Oct 2009' 'Feb 2004' 'Jul 2009' 'Jan 2007' 'Nov 2007' 'Dec 2007'
 'Jun 2002' 'Oct 2007' 'Jun 2007' 'Apr 2004' 'Aug 2006' 'May 2007'
 'Nov 2009' 'Feb 2009' 'Dec 2006' 'May 2006' 'Apr 2008' 'Sept 2008'
 'Mar 2005' 'Apr 2005' 'Nov 2006' 'Jan 2008' 'Jan 2005']

In [50]:
kolkata["Registration Year"].isna().sum()

35

In [51]:
kolkata["Registration Year"]=kolkata["Registration Year"].str.replace("'","").str.replace(" ","").str.replace("Jan","").str.replace("Feb","").str.replace("Mar","").str.replace("Apr","").str.replace("May","").str.replace("Jun","").str.replace("Jul","").str.replace("Aug","").str.replace("Sept","").str.replace("Oct","").str.replace("Nov","").str.replace("Dec","")

In [52]:
kolkata["Registration Year"]=kolkata["Registration Year"].fillna(2022)
kolkata["Registration Year"] = pd.to_numeric(kolkata["Registration Year"], errors='coerce')
kolkata["Registration Year"] =kolkata["Registration Year"].astype(int)

In [53]:
kolkata["Registration Year"] = pd.to_numeric(kolkata["Registration Year"], errors='coerce')
kolkata["Registration Year"].astype(int)

0       2015
1       2018
2       2018
3       2014
4       2015
        ...
8326    2022
8327    2014
8328    2011
8329    2012
8330    2017
Name: Registration Year, Length: 8331, dtype: int32

In [54]:
print(kolkata["Insurance Validity"].unique())
mode_vali = kolkata["Insurance Validity"].mode()[0]
kolkata["Insurance Validity"]=kolkata["Insurance Validity"].fillna(mode_vali)
ins=LabelEncoder()
kolkata["InsuranceValidity"]=ins.fit_transform(kolkata["Insurance Validity"])

['Third Party insurance' 'Comprehensive' 'Third Party' 'Zero Dep' nan '2'
 '1' 'Not Available']

In [55]:
kolkata=kolkata.drop(columns=["Insurance Validity"])

In [56]:
print(kolkata["Seats"].unique())

['5 Seats' '7 Seats' '4 Seats' '6 Seats' '8 Seats' '10 Seats' nan
 '9 Seats' '2 Seats']

In [57]:
kolkata["Seats"]=kolkata["Seats"].str.replace("Seats","").str.replace(" ","")
kolkata["Seats"] = pd.to_numeric(kolkata["Seats"], errors='coerce')
mode_value = kolkata["Seats"].mode()[0]
kolkata["Seats"]=kolkata["Seats"].fillna(mode_value).astype(int)

In [58]:
kolkata=kolkata.drop(columns=['Seats.1'])

In [59]:
kolkata["Kms Driven"]=kolkata["Kms Driven"].str.replace(",","").str.replace("Kms","")
kolkata["Kms Driven"] = pd.to_numeric(kolkata["Kms Driven"], errors='coerce')
model_value = kolkata["Kms Driven"].mean()
kolkata["Kms Driven"]=kolkata["Kms Driven"].fillna(model_value).astype("int")
kolkata["Kms Driven"]

0       120000
1        32706
2        11949
3        17794
4        60000
         ...
8326     10000
8327    120000
8328     50000
8329     40000
8330    120000
Name: Kms Driven, Length: 8331, dtype: int32

In [60]:
print(kolkata["RTO"].unique())

['KA51' 'KA05' 'KA03' 'KA53' 'KA04' nan 'KA01' 'OD02' 'KA41' 'KA02' 'HR26'
 'WB38' 'KA47' 'KA19' 'KA50' 'KA09' 'PY01' 'KA66' 'KA20' 'KA52' 'KA25'
 'KA27' 'TN09' 'KA13' 'MH46' 'KA42' 'KA12' 'KL07' 'KA55' 'KA07' 'KA17'
 'KA16' 'TN33' 'KA06' 'KA22' 'KA14' 'KA35' 'KA21' 'KA32' 'KL24' 'KA63'
 'KA26' 'KA11' 'KA36' 'KA40' 'KA18' 'DL14' 'UP32' 'KA34' 'KA45' 'AP39'
 'DL8C' 'MH48' 'TN14' 'MH03' 'TN10' 'WB26' 'WB08' 'MH31' 'KL60' 'WB12'
 'VK28' 'UP16' 'KL58' 'MP20' 'KA59' 'KA68' 'KA31' 'UP14' 'GJ06' 'UP70'
 'DL03' 'AP28' 'HR51' 'RJ05' 'HR13' 'CH01' 'MH04' 'JH01' 'KA33' 'TS07'
 'WB02' 'WB24' 'WB06' 'WB18' 'WB22' 'WB20' 'WB10' 'WB96' 'WB92' 'TN01'
 'UP33' 'AR01' 'WB36' 'WB42' 'WB16' 'WB40' 'WB34' 'WB74' 'WB98' 'UP81'
 'OD33' 'WB44' 'WB52' 'AS05' 'Wb24' 'MP09' 'Wb10' 'WB14' 'WB32' 'WB50'
 'WB94' 'Wb14' 'Wb26' 'GJ05' 'Wb08' 'Wb06' 'HP47' 'Wb02' 'Wb12' 'Wb52'
 'Wb16' 'wb02' 'Wb34' 'WB90' 'JH05' 'WB30' 'wb52' 'MH14' 'WW06' 'CG04'
 'AN01' 'WB68' 'WB04' 'WB84' 'GJ15' 'WB60' 'WB66' 'JH10' 'WB05' 'wb24'
 'wB24' 'WB03' 'BR01' 'wb06' 'DL2C' 'WB58' 'WB64' 'AS04' 'WB72' 'PB10'
 'DL01' 'DL4C' 'DL9X' 'DL10' 'DL3C' 'DL04' 'Up15' 'UP21' 'DL09' 'UK07'
 'UP80' 'HR72' 'HR98' 'DL26' 'PH65' 'Hr22' 'UP15' 'DD4L' 'DL9C' 'GJ01'
 'DL1C' 'DL6C' 'HP38' 'UP37' 'DL7C' 'DL5C' 'DL02' 'DL12' 'HR89' 'HR29'
 'HR12' 'TS09' 'UK14' 'HR36' 'HP01' 'UP01' 'HR06' 'HR01' 'MH01' 'HR87'
 'DL07' 'DL13' 'DL05' 'UK18' 'PB01' 'DL08' 'HP07' 'HR70' 'UP10' 'HR05'
 'UP12' 'DL1Z' 'HR16' 'DD8L' 'MP30' 'HP12' 'DL86' 'HP34' 'HP52' 'UP13'
 'DL11' 'PB70' 'DL3F' 'PY05' 'HR90' 'UP78' 'HR52' 'HP17' 'HR30' 'HP62'
 'UK17' 'HR19' 'PB08' 'HP05' 'HP93' 'HR03' 'MH05' 'TS08' 'MH02' 'UP25'
 'AS01' 'UP65' 'DL1V' 'DL5P' 'Dl12' 'DL1U' 'UP85' 'HR08' 'DL2B' 'DL9A'
 'HP15' 'HR81' 'UP53' 'MP07' 'UK08' 'HR10' 'DL16' 'PB03' 'HR24' 'HR78'
 'UK15' 'UK06' 'HR35' 'HR14' 'HR42' 'HP95' 'HR55' 'UP11' 'UP17' 'DL8A'
 'PB87' 'MP04' 'DD06' 'TS04' 'TS32' 'AP10' 'TS15' 'TS22' 'TS13' 'TS11'
 'TS28' 'TS30' 'TS10' 'TS27' 'TS16' 'TS17' 'TS05' 'TS23' 'TS06' 'AP11'
 'AP26' 'TS12' 'TS35' 'AP04' 'TS33' 'TS03' 'TS25' 'AP13' 'AP22' 'TS31'
 'AP07' 'AP16' 'TS29' 'AP09' 'TS02' 'AP29' 'TS19' 'AP20' 'TS34' 'AP36'
 'TS36' 'TS24' 'AP31' 'AP23' 'TS01' 'AP21' 'AP05' 'GA03' 'TA13' 'AP24'
 'AP12' 'AP27' 'TS21' 'TT07' 'KK04' 'TA10' 'AP25' 'TA07' 'AP02' 'TN07'
 'AP01' 'AA28' 'TN41' 'GJ04' 'TS26' 'TT02' 'TS18' 'TN39' 'TD07' 'AP37'
 'RJ13' 'RJ14' 'RJ32' 'RJ45' 'RJ19' 'RJ01' 'RJ27' 'RJ02' 'RJ37' '22BH'
 'RJ22' 'RJ23' 'RJ18' 'RJ42' 'RJ48' 'RJ10' 'RJ51' 'RJ40' 'HE26' 'RJ20'
 'RJ16' 'RR23' 'RJ07' 'RJ21' 'MP17' 'RJ29' 'RJ41' 'RJ36' 'RJ11' 'RJ44'
 'RJ06' 'RJ26' 'RH14' 'RJ25' 'PB22' 'RJ31' 'GJ10' 'RJ34' 'RJ28' 'RJ39'
 'RJ09' 'RJ04' 'RJ24' 'RJ53' 'PB65' 'RJ43' 'RJ12' 'RJ47' 'MP33' 'MH49'
 'HR27' 'RJ30' 'RJ52' 'GJ14' 'R14C' 'RJ4G' 'UP72' 'HR43' 'MP13' 'BR3F'
 'RJ35' 'MH18' 'UP64' 'UP82']

In [61]:
reg=kolkata["RTO"].mode()[0]
kolkata["RTO"]=kolkata["RTO"].fillna(reg)
gis=LabelEncoder()
kolkata["RTO"]=gis.fit_transform(kolkata["RTO"])

In [62]:
print(kolkata["Ownership"].unique())

['Third Owner' 'Second Owner' 'First Owner' 'Fourth Owner' 'Fifth Owner'
 nan]

In [63]:
own=kolkata["Ownership"].mode()[0]
kolkata["Ownership"]=kolkata["Ownership"].fillna(own)
kolkata["Ownership"]=kolkata["Ownership"].str.replace("First Owner","1").str.replace("Second Owner","2").str.replace("Third Owner","3").str.replace("Fourth Owner","4").str.replace("Fifth Owner","5")
kolkata["Ownership"]=pd.to_numeric(kolkata["Ownership"],errors='coerce')
kolkata["Ownership"]

0       3
1       2
2       1
3       1
4       1
       ..
8326    1
8327    1
8328    3
8329    1
8330    2
Name: Ownership, Length: 8331, dtype: int64

In [64]:
kolkata["Engine Displacement"]

0        998 cc
1       1497 cc
2       1199 cc
3       1197 cc
4       1248 cc
         ...
8326     998 cc
8327     796 cc
8328    1796 cc
8329    1197 cc
8330    1461 cc
Name: Engine Displacement, Length: 8331, dtype: object

In [65]:
kolkata["Engine Displacement"]=kolkata["Engine Displacement"].str.replace(",","").str.replace("cc","").str.replace(" ","")
kolkata["Engine Displacement"] = pd.to_numeric(kolkata["Engine Displacement"], errors='coerce')
model_value1 = kolkata["Engine Displacement"].mean()
kolkata["Engine Displacement"]=kolkata["Engine Displacement"].fillna(model_value1).astype(int)
kolkata["Engine Displacement"]

0        998
1       1497
2       1199
3       1197
4       1248
        ...
8326     998
8327     796
8328    1796
8329    1197
8330    1461
Name: Engine Displacement, Length: 8331, dtype: int32

In [66]:
manu=kolkata["Year of Manufacture"].mean()
kolkata["Year of Manufacture"]=kolkata["Year of Manufacture"].fillna(manu).astype(int)
kolkata["Year of Manufacture"]

0       2015
1       2018
2       2018
3       2014
4       2015
        ...
8326    2022
8327    2014
8328    2011
8329    2012
8330    2017
Name: Year of Manufacture, Length: 8331, dtype: int32

In [67]:
kolkata["Mileage"]

0        23.1 kmpl
1          17 kmpl
2       23.84 kmpl
3        19.1 kmpl
4       23.65 kmpl
           ...
8326    25.24 kmpl
8327    22.74 kmpl
8328    11.74 kmpl
8329     18.5 kmpl
8330    19.72 kmpl
Name: Mileage, Length: 8331, dtype: object

In [68]:
kolkata["Mileage"]=kolkata["Mileage"].str.replace(" kmpl","")
kolkata["Mileage"]

0        23.1
1          17
2       23.84
3        19.1
4       23.65
        ...
8326    25.24
8327    22.74
8328    11.74
8329     18.5
8330    19.72
Name: Mileage, Length: 8331, dtype: object

In [69]:
kolkata["Mileage"]=kolkata["Mileage"].str.replace(" kmpl","")
kolkata["Mileage"]=pd.to_numeric(kolkata["Mileage"],errors="coerce")
mil=kolkata["Mileage"].mean()
kolkata["Mileage"]=kolkata["Mileage"].fillna(mil).astype(int)

In [70]:
kolkata["Engine"]=kolkata["Engine"].str.replace(" CC","")
kolkata["Engine"]=pd.to_numeric(kolkata["Engine"],errors="coerce")
eng=kolkata["Engine"].mean()
kolkata["Engine"]=kolkata["Engine"].fillna(eng).astype(int)

In [71]:
kolkata=kolkata.drop(columns=["Engine"])

In [72]:
kolkata["Max Power"]

0        67.04bhp
1       121.31bhp
2           84bhp
3        81.86bhp
4         88.5bhp
          ...
8326     65.71bhp
8327      47.3bhp
8328       186bhp
8329     85.80bhp
8330    108.45bhp
Name: Max Power, Length: 8331, dtype: object

In [73]:
kolkata["Max Power.1"]

0        67.04bhp@6000rpm
1       121.31bhp@6500rpm
2           84bhp@6000rpm
3        81.86bhp@6000rpm
4         88.5bhp@4000rpm
              ...
8326     65.71bhp@5500rpm
8327      47.3bhp@6000rpm
8328       186bhp@5600rpm
8329     85.80bhp@6000rpm
8330    108.45bhp@4000rpm
Name: Max Power.1, Length: 8331, dtype: object

In [74]:
kolkata[['max_bhp1', 'MaxPower_rpm']] = kolkata['Max Power.1'].str.extract(r'([\d\.]+)bhp@([\d]+)rpm')

In [75]:
kolkata=kolkata.drop(columns=["max_bhp1"])

In [76]:
print(kolkata['MaxPower_rpm'].unique())

['6000' '6500' '4000' '3750' '5000' '3800' '5500' '6600' nan '5600' '4200'
 '6200' '5200' '3600' '4400' '3400' '6250' '6400' '5850' '3000' '6300'
 '3900' '5800' '3850' '3500' '5400' '5750' '3200' '5250' '7000' '5678'
 '4500' '5550' '6100' '5700' '5300' '4250' '61000' '6045']

In [77]:

kolkata["MaxPower_rpm"]=kolkata["MaxPower_rpm"].str.replace("rpm","")
kolkata["MaxPower_rpm"]=pd.to_numeric(kolkata["MaxPower_rpm"])
rpm=kolkata["MaxPower_rpm"].mean()
kolkata["MaxPower_rpm"]=kolkata["MaxPower_rpm"].fillna(rpm).astype(int)

In [78]:
kolkata=kolkata.drop(columns=["Max Power.1"])

In [79]:
kolkata["Max Power"]=kolkata["Max Power"].str.replace("bhp","")
kolkata["Max Power"]=pd.to_numeric(kolkata["Max Power"],errors="coerce")
max=kolkata["Max Power"].mean()
kolkata["MaxPowerbhp"]=kolkata["Max Power"].fillna(max).astype(float)

In [80]:
kolkata=kolkata.drop(columns=["Max Power"])

In [81]:
kolkata["Torque"]=kolkata["Torque"].str.replace("Nm","")
kolkata["Torque"]=pd.to_numeric(kolkata["Torque"],errors="coerce")
tor=kolkata["Torque"].mean()
kolkata["TorqueNm"]=kolkata["Torque"].fillna(tor).astype(float)

In [82]:
kolkata=kolkata.drop(columns=["Torque"])

In [83]:
kolkata["TorqueNm"]

0        90.00
1       150.00
2       114.00
3       113.75
4       200.00
         ...
8326     89.00
8327     69.00
8328    285.00
8329    114.00
8330    245.00
Name: TorqueNm, Length: 8331, dtype: float64

In [84]:
kolkata["Wheel Size"]=pd.to_numeric(kolkata["Wheel Size"],errors="coerce")
whe=kolkata["Wheel Size"].mean()
kolkata["Wheel Size"]=kolkata["Wheel Size"].fillna(whe)

In [85]:
kolkata["Color"]=kolkata["Color"].fillna("aquagreen")
col=LabelEncoder()
kolkata["ColorEncoded"]=col.fit_transform(kolkata["Color"])
kolkata["ColorEncoded"]

0       119
1       119
2        94
3        75
4        48
       ...
8326     75
8327     75
8328     75
8329     75
8330     75
Name: ColorEncoded, Length: 8331, dtype: int32

In [86]:
kolkata=kolkata.drop(columns=["Color"])

In [87]:
engtype=kolkata["Engine Type"].mode()[0]
kolkata["Engine Type"]=kolkata["Engine Type"].fillna(engtype)
englab=LabelEncoder()
kolkata["Engine Type"]=englab.fit_transform(kolkata["Engine Type"])

In [88]:
kolkata["Engine Type"]

0       274
1       372
2       333
3       301
4       201
       ...
8326    277
8327    234
8328    178
8329    270
8330    437
Name: Engine Type, Length: 8331, dtype: int32

In [89]:
dis=kolkata["Displacement"].mean()
kolkata["Displacement"]=kolkata["Displacement"].fillna(dis)

In [90]:
kolkata=kolkata.drop(columns=["Displacement"])

In [91]:
print(kolkata["Max Torque"].unique())

['90Nm@3500rpm' '150Nm@4500rpm' '114Nm@3500rpm' '113.75Nm@4000rpm'
 '200Nm@1750rpm' '350Nm@1750-2500rpm' '104Nm@4000rpm'
 '171.6Nm@1500-4000rpm' '138Nm@4400rpm' '115Nm@4000rpm' '113.75nm@4000rpm'
 '110Nm@4800rpm' '330Nm@1600-2800rpm' '400Nm@1600-2600rpm'
 '219.6Nm@1500-2750rpm' '170Nm@1750-4000rpm' '145Nm@4600rpm'
 '35.7 @ 1,750-3,000 (kgm@rpm)' '113Nm@4400rpm' '142Nm @ 4000RPM'
 '700Nm@1800-3500rpm' '99Nm@4500 rpm' '96.1Nm@3000rpm'
 '300Nm@1600-4000rpm' '380Nm@1750-2500rpm' '400Nm@1600-2800rpm'
 '350Nm@1450-4800rpm' '343 Nm @ 1400-3400 rpm' '245Nm@1750rpm'
 '114.7Nm@4000rpm' '219.7Nm@1500-2750rpm' '177.5Nm@4700rpm'
 '400Nm@1750-3000rpm' '69Nm@3500rpm' '290Nm@1800-2800rpm' '280Nm@1250rpm'
 '242nm@1500-3200rpm' '600Nm@1200-3200rpm' '62Nm@3000rpm' '117nm@4000rpm'
 '619Nm@1600-2400rpm' '550Nm@1750-2750rpm' '91Nm@4250rpm'
 '260Nm@1500-2750rpm' '115 Nm @ 3200 rpm ' '89Nm@3500rpm'
 '250Nm@1500-2500rpm' '149Nm@4500rpm' '259.9Nm@1900-2750rpm'
 '190Nm@2000rpm' '400Nm@1750-2500rpm' '250Nm@1250-5000rpm' '114Nm@4000rpm'
 '171.62nm@1500-4000rpm' '146Nm@4800rpm' '175Nm@1500-4100rpm'
 '160Nm@1500-2750rpm' '113.7Nm@4000rpm' '190Nm@1750-2250rpm'
 '99.04Nm@4500rpm' '400Nm' '620Nm@1600-2400rpm' '200Nm@2000-3500rpm'
 '250nm@1600-3600rpm' '109Nm@4500rpm' '113Nm@4200rpm' '96Nm@3500rpm'
 '74.5Nm@4000rpm' '140Nm@4200rpm' '191nm@4500rpm' '151NM@4850rpm'
 '242Nm@1500-3200rpm' '250nm@1500-3500rpm' '34.7 @ 1,750-3,000 (kgm@rpm)'
 '250Nm@2500-4000rpm' '320Nm@1750-2500rpm' '111.8Nm@4000rpm'
 '145Nm@3750rpm ' '11.4 kgm at 4,000 rpm' '470Nm@1750-2500rpm'
 '112Nm@4000rpm' '250Nm@1500-2750rpm' '111.7Nm@4000rpm'
 '560Nm@1500-3000rpm' '380Nm@1750-3000rpm' '400.11Nm@1750-2750rpm'
 '420Nm@1400-2600rpm' '250Nm@1600-3600rpm' '151Nm@4850rpm'
 '400Nm@1400-2800rpm' '248Nm@2250rpm' '218Nm@4200rpm' '230Nm@1500-2500rpm'
 '250Nm@1620-4000rpm' '181Nm@4000rpm' '436.4Nm@1800-2500rpm'
 '400Nm@1550-4400rpm' '150Nm@1700-4500rpm' '240Nm@1750rpm' '200Nm@1900rpm'
 '320Nm@1600-2800rpm' '259.87nm@1500-3000rpm' '140Nm@4400rpm'
 '115 Nm @ 4500 rpm' '220Nm@1500-2750rpm' '402Nm@1600-3000rpm'
 '205Nm@1750-3250rpm' '170nm@1750-4000rpm' '500Nm@1600-1800rpm'
 '205Nm@1800-2800rpm' '200Nm@1200-3600rpm' '130Nm@4000rpm'
 '10.7 @ 2,500 (kgm@rpm)' '620Nm@1500-2500rpm' '17.8 @ 4,250 (kgm@rpm)'
 '450Nm@2000rpm' '175nm@1750-4000rpm' '84Nm@3500rpm' '172Nm@1500-4000rpm'
 '320Nm@1750-3000rpm' '240.26nm@1500-2750rpm' '178Nm@1750-4500rpm'
 '25.1 @ 4,000 (kgm@rpm)' '144Nm@4400rpm' '124.5Nm@3500rpm'
 '300Nm@1500-2500rpm' '130 Nm @ 3000 rpm ' '180Nm@2000rpm'
 '200Nm@1250-4000rpm' '154.9Nm@4200rpm' '440nm@1750-2750rpm'
 '25.5@1,900 (kgm@rpm)' '250@1250-5000rpm' '207Nm@2200rpm'
 '620Nm@2000-2500rpm' '25.5 @ 2,750-4,250 (kgm@rpm)' '200Nm@1400-3400rpm'
 '360Nm@1750-2800rpm' '175Nm@1750-4000rpm' '240Nm@1600-5000rpm '
 '420Nm@1750rpm' '110Nm@3000-4300rpm' '95Nm@2950-3800rpm'
 '360Nm@1400-3200rpm' '20.4@1400-3400 (kgm@rpm)' '254NM @ 1600rpm'
 '115Nm@3500-3600rpm' '152Nm@2200-4400rpm' '300Nm' '143.8Nm@4500rpm'
 '148Nm@3750rpm' '11.4 @ 4,000 (kgm@rpm)' '22.9@1,950-4,700 (kgm@rpm)'
 '160Nm@2000rpm' '200Nm@1500-4000rpm' '119Nm@4250rpm'
 '259.8Nm@1900-2750rpm' '380Nm@2500rpm' '215Nm@1750-3000rpm'
 '215Nm@1750-2500rpm' '250nm@1500-2750rpm' '145Nm@4300rpm'
 '430Nm@1750-2500rpm' '151nm@4850rpm' '160Nm@2800-3600rpm' '142Nm@4000rpm'
 nan '35.7@1,250 (kgm@rpm)' '153Nm@3800rpm' '110Nm@3750rpm'
 '113nm@3300rpm' '145Nm@3750rpm' '320Nm@1500-3000rpm' '114.73nm@4000rpm'
 '224nm@1500-2750rpm' '620Nm@1600rpm' '400nm@2800rpm' '138nm@4400rpm'
 '144nm@4500rpm' '250Nm@1750-2500rpm' '300Nm@1600-3000rpm'
 '114.73Nm@4000rpm' '226Nm@4400rpm' '70Nm@1000rpm' '110Nm' '102Nm@4000rpm'
 '6.1 kgm @ 3000 rpm' '113Nm@3300rpm' '320Nm@1500-4100rpm' '250Nm'
 '114.74Nm@4200rpm' '250Nm@1500-3000rpm' '140Nm@1800-3000rpm'
 '245Nm@4000rpm' '180.4Nm@1750-2500rpm' '245nm@4000rpm' '245Nm'
 '13.1 kgm @ 4600 rpm' '11.5@4,500 (kgm@rpm)' '144Nm@4500rpm'
 '204Nm@2000-2750rpm' '360Nm@1200-3400rpm' '327Nm@2600rpm' '224Nm@4000rpm'
 '212Nm@2000-4000rpm' '240Nm@1600-2800rpm' '108Nm@4400rpm' '173Nm@4000rpm'
 '85Nm@2500rpm' '109Nm@4600rpm' '98Nm@3000rpm' '400Nm@2000rpm'
 '450Nm@1750-2800rpm' '113.8nm@4000rpm' '14.9 KGM at 3000 RPM'
 '78 Nm @ 4500 rpm ' '343Nm@1400-2800rpm' '110 Nm @ 3200 rpm'
 '12.7 @ 2,700 (kgm@rpm)' '319Nm@1800-2800rpm' '130@2500(kgm@rpm)'
 '260 Nm at 1800-2200 rpm' '190Nm@1750-3000rpm' '182.5Nm@1500-1800rpm'
 '222Nm@4300rpm' '85Nm@3000rpm' '121.5Nm@4200rpm' '122Nm@4000rpm'
 '365@1200-4500rpm' '90.3Nm@4200rpm' '113Nm@4500rpm' '171Nm@1800rpm'
 '450Nm@1500-5200rpm' '11@3,000 (kgm@rpm)' '91Nm@2500 rpm'
 '126 Nm @ 3200 rpm' '115Nm@3750rpm' '4.8 kgm@3000 rpm'
 '240Nm@1500-2750rpm' '195Nm@1400-2200rpm' '116Nm@4750rpm'
 '25.2 @ 1,500â€“4,500 (kgm@rpm)' '12.5@3,000 (kgm@rpm)'
 '14.9 @ 3,400 (kgm@rpm)' '153Nm@3750-3800rpm' '250Nm@1500-4500rpm'
 '200Nm@1400-2200rpm' '197Nm@1750rpm' '259.87NM@1500-3000rpm'
 '25 @ 1,800-2,800 (kgm@rpm)' '113.76nm@4000rpm' '380Nm@1750-2750rpm'
 '136.8Nm@4400rpm' '72Nm@4386rpm' '35.0 @1,750 (kgm@rpm)' '380Nm@2000rpm'
 '172.5 Nm@1750rpm' '219.6Nm@1750-2750rpm' '51Nm@4000+/-500rpm'
 '320nm@1500-4100rpm' '136Nm@4250rpm' '146Nm at 4800 rpm'
 '300Nm@1600-2800rpm' '300Nm@1750-2500rpm' '13.5@2,500 (kgm@rpm)'
 '515Nm@3500rpm' '155 Nm at 1600-2800 rpm' '25.5 @ 1,500-3,000 (kgm@rpm)'
 '135Nm@2500rpm' '72Nm@4250rpm' '172nm@1500-4000rpm' '200Nm@2000rpm'
 '12.5 @ 3,500 (kgm@rpm)' '300Nm@1250-3000rpm' '259.87Nm@1900-2750rpm'
 '42 @ 2,000 (kgm@rpm)' '91nm@4250rpm' '95Nm@3000-4300rpm'
 '420Nm@1600-2800rpm' '16.3 @ 2,000 (kgm@rpm)' '520Nm@2000-4200rpm'
 '190Nm@1750rpm' '9.4 @ 2,750 (kgm@rpm)' '132Nm@3000rpm'
 '170Nm@1800-2400rpm' '219.66nm@1500-2750rpm' '180Nm@1440-1500rpm'
 '170Nm@1400-4500rpm' '320Nm@1700-2700rpm' '300Nm@1200-4000rpm'
 '247Nm@1800-2000rpm' '220Nm@1350-4300rpm' '420Nm@1900-2800rpm'
 '120Nm@4250rpm' '540Nm@1750-3000rpm' '373.5Nm@1500-2400rpm'
 '440Nm@1750-2750rpm' '343Nm@1400-3400rpm' '280Nm@2400-2800rpm'
 '400Nm@1500-4000rpm' '60Nm@3500rpm' '209Nm@2000rpm' '280Nm@1350rpm'
 '500Nm@1400-3250rpm' '250Nm@1500-3500rpm' '240 Nm @ 2000 rpm'
 '145@4,100 (kgm@rpm)' '213Nm@4500rpm' '450Nm@1600-2400rpm'
 '22.4 kgm at 1750-2750rpm' '17.5 @ 4,300 (kgm@rpm)' '115Nm@4500rpm'
 '400Nm@3000rpm' '99.07Nm@4500 rpm' '82.1Nm@3400rpm' '130 Nm @ 3000 rpm'
 '192.2Nm@4000rpm' '440Nm' '440Nm@1500-3000rpm' '19 @ 1,800 (kgm@rpm)'
 '350Nm@1750-2500 rpm' '365nm@1500rpm' '480nm@1500-2400rpm' '95Nm@3500rpm'
 '280Nm@1800-2800rpm' '190.24nm@1750-2250rpm' '320Nm@1400-4100rpm'
 '134Nm@4000rpm' '350nm@1750-2500rpm' '115@2,500 (kgm@rpm)'
 '370Nm@1600-4500rpm' '200Nm@1750-3000rpm' '259.88Nm@1900-2750rpm'
 '108.5Nm@5000rpm' '320Nm@1650-4000rpm' '320Nm' '85.32Nm@4500 rpm'
 '340Nm@1750rpm' '500Nm @3500-5000rpm' '171.62Nm@1500-4000rpm'
 '250Nm@4250rpm' '320nm@1500–4180rpm' '106 Nm @ 2200 rpm' '142Nm@4000RPM'
 '200Nm@1250-3000rpm' '104Nm@3100rpm' '650Nm@1750-4750rpm' '480Nm'
 '420Nm@1600-2600rpm' '106.5Nm@4400rpm' '78Nm@3500rpm' '192Nm@4000rpm'
 '450Nm@1750-2500rpm' '320Nm@1400-3700rpm' '142.5Nm@1750rpm'
 '500Nm@1370-4500rpm' '12.9 @ 3,500 (kgm@rpm)' '124.6Nm@3500rpm'
 '171.6Nm@4300rpm' '650Nm @1750-2500rpm' '132.38Nm@4000rpm'
 '115Nm@3250+/-100rpm' '135.4Nm@2500' '204Nm @ 2000-2750rpm'
 '220Nm@1500-2700rpm' '400nm@1750–2500rpm' '16@2,000 (kgm@rpm)'
 '113Nm @ 4,500rpm' '190 Nm at 1750 rpm ' '260Nm@1750-2250rpm'
 '440Nm@1800-2800rpm' '260nm@1500-2750rpm' '140Nm@1500-4000rpm'
 '122Nm@4400-4800rpm' '400Nm@1750-2750rpm' '350Nm@1500-3500rpm'
 '24 @ 1,900-2,750 (kgm@rpm)' '62@3,000 (Nm@rpm)' '340Nm@1500-4000rpm'
 '7.8@4,500 (kgm@rpm)' '220Nm@3600rpm' '104.4Nm@3000rpm'
 '460Nm@3500-5000rpm' '170Nm' '101Nm@3000rpm' '500Nm@1600-2800rpm'
 '385Nm@1600-2500rpm' '172Nm@4300rpm' '200Nm@3600rpm' '355Nm@4500rpm'
 '218Nm@1400-2600rpm' '350Nm@1400-3400rpm' '340Nm@1500-4500rpm'
 '350Nm@1500-4200rpm' '300Nm@1200-1400rpm' '135.3Nm@5000rpm'
 '113.8Nm@4000rpm' '233Nm@4100rpm' '110 (11.2) @ 4800' '96Nm @ 2500rpm'
 '97.96Nm@4200rpm' '59Nm@2500rpm' '285Nm@2400-4000rpm'
 '320nm@1650-4000rpm' '115Nm@4200rpm' '95.2nm@4000rpm' '95.2Nm@4000rpm'
 '240nm@1500-2750rpm' '270Nm@1000rpm' '450Nm@1380-5000rpm'
 '380nm@1800-2800rpm' '320Nm@1500-2800rpm' '84.33Nm@4500 rpm'
 '122Nm@4400rpm' '370Nm@1750-3000rpm' '400Nm@2000-2500rpm'
 '500Nm@1600-2400rpm' '490Nm@1600rpm' '335Nm@4600rpm' '226Nm @ 4100rpm'
 '600Nm@1750-2250rpm' '360Nm@1500–2500rpm' '500Nm@1600-4500rpm'
 '580Nm@1400-3250rpm' '134.2nm@4000rpm' '280Nm@1250-4600rpm'
 '430Nm@1400rpm' '500Nm@1600-4000rpm' '420Nm@1400-3400rpm'
 '478.5Nm@1500-2400rpm' '430Nm@1750-2500' '600Nm@1500-3000rpm'
 '400Nm@3000-4000rpm' '550Nm@1750-2750pm' '850nm@2500–3500rpm'
 '500Nm@1370-4500' '95@4000rpm' '700nm@2000-4000rpm' '125Nm@2000rpm'
 '475Nm@2250-5000rpm' '190Nm@4300rpm' '520Nm@1850-5000rpm'
 '8.6@3,500 (kgm@rpm)' '480Nm@1600-4000rpm' '280Nm@3000-4000rpm'
 '400nm@1550-4400rpm' '320Nm@1450–4200rpm' '350Nm@1500-3000rpm'
 '153Nm@3000rpm' '110 @ 3,750 (Nm@rpm)' '240Nm@4296-4500rpm'
 '253Nm@1500-3500rpm' '620Nm@1500–2500rpm' '700Nm@1600-2600rpm'
 '280nm@1350-4600rpm' '320Nm@1500-4000rpm' '370Nm@3500-5250rpm'
 '430nm@1750-2500rpm' '192.21Nm@4000rpm' '360Nm@1400-2600rpm'
 '320nm@1450–4200' '370Nm@1300-4000rpm' '320Nm@1450-4200rpm'
 '520 Nm@2000-4200rpm' '94.14Nm@3500rpm' '153 Nm at 3800 rpm'
 '250Nm@1600-3500rpm' '320Nm@1800-2800rpm' '225Nm@4000rpm'
 '300Nm@1800-4000rpm' '99.1Nm@4500rpm' '148Nm@4000rpm' '98.5Nm@4300rpm'
 '98Nm@4000rpm' '140Nm@1500-5500rpm' '160Nm@1750rpm' '250nm@2500-4000rpm'
 '24.5 @ 3,500-4,500 (kgm@rpm)' '104Nm@4400rpm' '450Nm@1500rpm'
 '77Nm@3500rpm' '400Nm@1400-2800' '174Nm@4300rpm' '370Nm@1600-4300bhp'
 '345Nm@4500rpm' '250Nm@1400-2800rpm' '114.74nm@4200rpm' '146Nm@3400rpm'
 '147.6Nm@2000-4500rpm' '221Nm@3600-5200rpm' '689Nm@1800rpm'
 '175nm@1500-4100rpm' '320Nm@1400-3500rpm' '153Nm@3750rpm' '54Nm@3000rpm'
 '420Nm@2000rpm' '420Nm@2000-2500rpm' '450Nm@3500-5000rpm'
 '400Nm@1500-2500rpm' '96Nm@2500rpm' '200 Nm @ 1750-3000 rpm'
 '143.8nm@4500rpm' '254Nm@1600rpm' '225Nm@1500-2500rpm' '113nm@4200rpm'
 '520Nm@2500-5000rpm' '14.9 @ 3,000 (kgm@rpm)' '103Nm@4500rpm'
 '600Nm@2000rpm' '510 @ 1600-2400' '50@1600-1800 (kgm@rpm)'
 '250Nm@1620–4000rpm' '400Nm@1500-2850rpm' '150Nm@1750rpm'
 '23.6 @ 4,250 (kgm@rpm)' '215nm@1750-2500rpm' '140Nm@4500rpm'
 '450nm@3500-5000rpm' '440Nm@1500rpm' '320Nm @1750rpm'
 '13.5 @ 4,800 (kgm@rpm)' '127nm@4500-5000' '420Nm@1500-3250rpm'
 '250Nm @1900rpm' '350Nm@1500-2750rpm' '132.3Nm@4000rpm' '480Nm@1750rpm'
 '28.3 @ 1,700-2,200 (kgm@rpm)' '265Nm@1500-3000rpm' '210/1750-4600'
 '280Nm' '135.4Nm@2500rpm ' '91Nm@3000rpm' '370Nm@1500-3000rpm' '760Nm'
 '210 / 1900' '400Nm@1500-2750rpm' '210nm@2000-4000rpm'
 '250nm@1500-3000rpm' '187  Nm @ 2500  rpm' '11.8 @ 3,200 (kgm@rpm)'
 '190 Nm @2000 rpm' '250Nm@1000-2000rpm' '12@3,500 (kgm@rpm)'
 '424Nm@2000rpm' '90.3 Nm @ 4200 rpm' '200Nm @1250-4000rpm'
 '148  Nm @ 3500  rpm' '151 Nm @ 2400 rpm' '190.25nm@1750-2250rpm'
 '16.1@4,200 (kgm@rpm)' '85Nm@3500rpm ' '20 @ 4,700 (kgm@rpm)'
 '340nm@1750-3000rpm' '145Nm@4100rpm' '360Nm@2000rpm' '500Nm@1900-5000rpm'
 '275Nm@2000rpm' '250Nm @1900rpm ' '370Nm@1300-4000' '88.4Nm@4200rpm'
 '190Nm@4200rpm' '110Nm@4400rpm' '382nm@1750-2250rpm' '395Nm'
 '110 Nm at 3750 rpm' '219.7Nm@1750-2750rpm' '436.39Nm@1800-2500rpm'
 '180 Nm at 1440-1500rpm' '9.8 @ 3,000 (kgm@rpm)' '10.4 @ 3,200 (kgm@rpm)'
 '190 Nm at 1750  rpm ' '13@3,100 (kgm@rpm)' '25.5 @ 1,900 (kgm@rpm)'
 '11.3 kgm @ 4700 rpm' '110 Nm @ 4500 rpm ' '210Nm@1600-2200rpm'
 '530Nm@2300-5000' '600Nm@2000-4500rpm' '134.2Nm@4000rpm']

In [92]:
kolkata['Max Torque'] = kolkata['Max Torque'].fillna('0')

In [93]:
kolkata['Max Torque'].isnull().sum()

0

In [94]:
#kolkata['Max Torque'] = kolkata['Max Torque'].str.replace('Nm@rpm','').str.replace('kgm@rpm','').str.replace('-','').str.replace(',','').str.replace('()','').str.replace(' ','').str.replace('RPM','').str.replace('NM','').str.replace('nm','').str.replace('at','')

In [95]:
kolkata[['Torque_Nm1', 'Torque_rpm']] = kolkata['Max Torque'].str.extract(r'(\d+Nm)@(\d+rpm)')

In [96]:
kolkata=kolkata.drop(columns=["Torque_Nm1"])

In [97]:
print(kolkata["Torque_rpm"].unique())
kolkata["Torque_rpm"]=kolkata["Torque_rpm"].str.replace("rpm","")
kolkata["Torque_rpm"]=pd.to_numeric(kolkata["Torque_rpm"])
rpm=kolkata["Torque_rpm"].mean()
kolkata["Torque_rpm"]=kolkata["Torque_rpm"].fillna(rpm).astype(int)

['3500rpm' '4500rpm' '4000rpm' '1750rpm' nan '4400rpm' '4800rpm' '4600rpm'
 '3000rpm' '4700rpm' '1250rpm' '4250rpm' '2000rpm' '4200rpm' '3750rpm'
 '4850rpm' '2250rpm' '1900rpm' '2200rpm' '2500rpm' '4300rpm' '3800rpm'
 '1600rpm' '1000rpm' '3300rpm' '2600rpm' '1800rpm' '4750rpm' '4386rpm'
 '1350rpm' '3400rpm' '5000rpm' '3100rpm' '3600rpm' '4100rpm' '1400rpm'
 '1500rpm']

In [98]:
print(kolkata["Torque_rpm"].unique())

[3500 4500 4000 1750 3733 4400 4800 4600 3000 4700 1250 4250 2000 4200
 3750 4850 2250 1900 2200 2500 4300 3800 1600 1000 3300 2600 1800 4750
 4386 1350 3400 5000 3100 3600 4100 1400 1500]

In [99]:
kolkata=kolkata.drop(columns=['Max Torque'])

In [100]:
#kolkata['Max Torque'] = kolkata['Max Torque'].str.replace("@","").str.replace("Nm","").str.replace("KGM","").str.replace("RPM","").str.replace("â€“","").str.replace("+/","").str.replace("-","").str.replace('"','').str.replace("â€“","").str.replace("â€“","").str.replace("â€“","").str.replace("â€“","").str.replace("â€“","").str.replace("â€“","")

In [101]:
print(kolkata["No of Cylinder"].unique())

[ 3.  4.  8.  6.  5. nan 23.  2.  7.]

In [102]:
kolkata["No of Cylinder"]
cyl=kolkata["No of Cylinder"].mean()
kolkata["NoOfCylinder"]=kolkata["No of Cylinder"].fillna(whe).astype(int)

In [103]:
print(kolkata["NoOfCylinder"].unique())

[ 3  4  8  6  5 15 23  2  7]

In [104]:
print(kolkata["Values per Cylinder"].unique())

[ 4.  3.  2.  5. nan 69.]

In [105]:
kolkata["Values per Cylinder"]
val=kolkata["Values per Cylinder"].mean()
kolkata["Values per Cylinder"]=kolkata["Values per Cylinder"].fillna(val).astype(int)

In [106]:
print(kolkata["Value Configuration"].unique())

['DOHC' nan 'SOHC' 'DOHC ' 'undefined' 'DOHC with VIS'
 '16 Modules 48 Cells' 'iDSI' '23 Modules 69 Cells' 'DOHC with VGT'
 '16-valve DOHC layout' 'DOHC with TIS' 'VTEC' 'SOHC ']

In [107]:
valu=kolkata["Value Configuration"].mode()[0]
kolkata["Value Configuration"]=kolkata["Value Configuration"].fillna(valu)
con=LabelEncoder()
kolkata["ValueConfigurationEncoded"]=con.fit_transform(kolkata["Value Configuration"])

In [108]:
kolkata=kolkata.drop(columns=["Value Configuration"])

In [109]:
print(kolkata["Fuel Suppy System"].unique())

['MPFi' 'Direct Injection' nan 'CRDI' 'Electronic Injection System' 'GDi'
 'MPFI' 'PGM - Fi' 'Direct Injection ' 'PGM-Fi' 'CRDi'
 'Multi Point Fuel Injection' 'MPFI+LPG' 'Common-Rail type'
 'Common Rail Direct Injection (dCi)' 'Multipoint Injection' 'CDI' 'PFI'
 'EFI(Electronic Fuel Injection)' 'MPFI ' 'EFI' 'Multi-point injection'
 'TSI' 'TDCi' 'Common rail direct injection'
 'PGM-FI (Programmed Fuel Injection)' 'Electronic Fuel Injection'
 'Common Rail Direct Injection' 'Common Rail' 'SEFI'
 'Multi point Fuel Injection' 'MPI' 'Gasoline Direct Injection' 'MPi'
 'Direct Injection Common Rail' '3 Phase AC Induction Motors' 'Dual VVT-i'
 'EFI (Electronic Fuel Injection)' 'SMPI' 'Indirect Injection'
 'common rail system' 'GDI' 'Electronic Fuel Injection(EFI)'
 'PGM-FI (Programmed Fuel Inject' 'Direct Fuel Injection' 'TFSI'
 'Common Rail Injection' 'TDi' 'TGDi' 'PGM-FI' 'Common Rail Diesel' 'DPFi'
 'ISG' 'Advanced Common Rail' 'EGIS' 'Common Rail '
 'EFI (Electronic Fuel Injection' 'Mpfi' 'Direct Injection Common Rail '
 'DEDST' 'CRDI ' 'D-4S' 'CNG' 'Multipoint injection' 'Direct injection'
 'Intelligent-Gas Port Injection' 'DDIS' 'gasoline direct injection'
 'MPFi ' 'EFIC' 'MPFI+CNG' 'Common-Rail Type' 'VVT-iE' 'Direct Injectio'
 'Ti-VCT' 'PGM-FI (Programmed Fuel Inje' 'Electric'
 'Distribution Type Fuel Injection']

In [110]:
sys=kolkata["Fuel Suppy System"].mode()[0]
kolkata["Fuel Suppy System"]=kolkata["Fuel Suppy System"].fillna(sys)
suppy=LabelEncoder()
kolkata["Fuel Suppy System encoded"]=suppy.fit_transform(kolkata["Fuel Suppy System"])

In [111]:
kolkata=kolkata.drop(columns=["Fuel Suppy System"])

In [112]:
#kolkata["BoreX Stroke"]=kolkata["BoreX Stroke"].str.replace("mm","").str.replace("X","").str.replace(" ","").str.replace("x","").str.replace("/","").str.replace("()","").str.rstrip(".")

In [113]:
#kolkata["BoreX Stroke"]=pd.to_numeric(kolkata["BoreX Stroke"],errors="coerce")
#bor=kolkata["BoreX Stroke"].mode()[0]
#kolkata["BoreX Stroke"]=kolkata["BoreX Stroke"].fillna(bor)

In [114]:
#kolkata["BoreXStroke"]=kolkata["BoreX Stroke"].round(3).astype(float)

In [115]:
#kolkata=kolkata.drop(columns=["BoreX Stroke"])

In [116]:
#kolkata["BoreXStroke"]

In [117]:
#kolkata["Compression Ratio"]
#olkata["Compression Ratio"]=pd.to_numeric(kolkata["Compression Ratio"],errors='coerce')Ratio=kolkata["Compression Ratio"].mean()kolkata["Compression Ratio"]=kolkata["Compression Ratio"].fillna(Ratio)

In [118]:
kolkata["Turbo Charger"]

0        No
1        No
2        No
3        No
4       Yes
       ...
8326    NaN
8327     No
8328     No
8329     No
8330    Yes
Name: Turbo Charger, Length: 8331, dtype: object

In [119]:
print(kolkata["Turbo Charger"].unique())

['No' 'Yes' 'NO' nan 'Twin' 'YES' 'no' 'Turbo' 'yes' 'twin']

In [120]:
turbo=kolkata["Turbo Charger"].mode()[0]
kolkata["Turbo Charger"]=kolkata["Turbo Charger"].fillna(turbo)
kolkata["Turbo Charger"]=kolkata["Turbo Charger"].str.replace("no","No").str.replace("NO","No").str.replace("YES","yes").str.replace("twin","Twin").str.replace("Yes","yes")
tur=LabelEncoder()
kolkata["Turbo Charger"]=tur.fit_transform(kolkata["Turbo Charger"])

In [121]:
print(kolkata["Turbo Charger"].unique())

[0 3 2 1]

In [122]:
print(kolkata["Super Charger"].unique())

['No' nan 'Yes' 'yes' 'no' 'NO']

In [123]:
super=kolkata["Super Charger"].mode()[0]
kolkata["Super Charger"]=kolkata["Super Charger"].fillna(super)
kolkata["Super Charger"]=kolkata["Super Charger"].str.replace("no","No").str.replace("NO","No").str.replace("Yes","yes")
kolkata["Super Charger"]=kolkata["Super Charger"].apply([lambda x:1 if x=="yes" else 0])

In [124]:
print(kolkata["Super Charger"].unique())

[0 1]

In [125]:
kolkata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8331 entries, 0 to 8330
Data columns (total 54 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   bt                         8331 non-null   object
 1   km                         8331 non-null   int32
 2   transmission               8331 non-null   object
 3   ownerNo                    8331 non-null   int64
 4   owner                      8331 non-null   object
 5   modelYear                  8331 non-null   int64
 6   centralVariantId           8331 non-null   int64
 7   price                      8331 non-null   float64
 8   trendingText               8331 non-null   object
 9   Registration Year          8331 non-null   int32
 10  Fuel Type                  8331 non-null   object
 11  Seats                      8331 non-null   int32
 12  Kms Driven                 8331 non-null   int32
 13  RTO                        8331 non-null   int32
 14  Ownership                  8331 non-null   int64
 15  Engine Displacement        8331 non-null   int32
 16  Year of Manufacture        8331 non-null   int32
 17  Mileage                    8331 non-null   int32
 18  Wheel Size                 8331 non-null   float64
 19  Engine Type                8331 non-null   int32
 20  No of Cylinder             8295 non-null   float64
 21  Values per Cylinder        8331 non-null   int32
 22  Turbo Charger              8331 non-null   int32
 23  Super Charger              8331 non-null   int64
 24  Length                     8254 non-null   object
 25  Width                      8251 non-null   object
 26  Height                     8254 non-null   object
 27  Wheel Base                 8179 non-null   object
 28  Front Tread                4823 non-null   object
 29  Rear Tread                 4817 non-null   object
 30  Kerb Weight                8279 non-null   object
 31  Seating Capacity.1         5360 non-null   float64
 32  Steering Type.1            5167 non-null   object
 33  Tyre Type.1                5312 non-null   object
 34  No Door Numbers.1          5355 non-null   float64
 35  Gear Box                   5651 non-null   object
 36  Drive Type                 4582 non-null   object
 37  Turning Radius             4646 non-null   object
 38  Front Brake Type           5666 non-null   object
 39  Rear Brake Type            5666 non-null   object
 40  Cargo Volumn               6670 non-null   object
 41  city                       8331 non-null   object
 42  car_names_encoded          8331 non-null   int32
 43  Model_encoded              8331 non-null   int32
 44  variantName_encoded        8331 non-null   int32
 45  InsuranceValidity          8331 non-null   int32
 46  MaxPower_rpm               8331 non-null   int32
 47  MaxPowerbhp                8331 non-null   float64
 48  TorqueNm                   8331 non-null   float64
 49  ColorEncoded               8331 non-null   int32
 50  Torque_rpm                 8331 non-null   int32
 51  NoOfCylinder               8331 non-null   int32
 52  ValueConfigurationEncoded  8331 non-null   int32
 53  Fuel Suppy System encoded  8331 non-null   int32
dtypes: float64(7), int32(21), int64(5), object(21)
memory usage: 2.8+ MB

In [126]:
print(kolkata["Seating Capacity.1"].unique())

[nan  5.  7.  8.  6. 10.  4.  9.  2.]

In [127]:
seat=kolkata["Seating Capacity.1"].mean()
kolkata["Seating Capacity.1"]=kolkata["Seating Capacity.1"].fillna(seat)
cap=LabelEncoder()
kolkata["SeatingCapacityEncoded"]=cap.fit_transform(kolkata["Seating Capacity.1"])

In [128]:
kolkata=kolkata.drop(columns=["Seating Capacity.1"])

In [129]:
print(kolkata["Steering Type.1"].unique())

[nan 'Power' 'Electric' 'Manual' 'power' 'Electrical' 'Electronic' 'EPAS']

In [130]:
ste=kolkata["Steering Type.1"].mode()[0]
kolkata["Steering Type.1"]=kolkata["Steering Type.1"].fillna(ste)
kolkata["Steering Type.1"]=kolkata["Steering Type.1"].str.replace("power","Power")
stee=LabelEncoder()
kolkata["SteeringTypeEncoded"]=stee.fit_transform(kolkata["Steering Type.1"])

In [131]:
kolkata=kolkata.drop(columns=["Steering Type.1"])

In [132]:
print(kolkata["Tyre Type.1"].unique())

[nan 'Tubeless,Radial' 'Tubeless, Radial' 'Tubeless Tyres, Radial'
 'Tubeless' 'Radial, Tubless' 'Radial, Tubeless' 'Tubless, Radial'
 'Tubeless, Runflat' 'Tubeless Tyres Mud Terrain' 'Tubeless,Radials'
 'Tubeless Tyres' 'tubeless tyre' 'Radial,Tubeless' 'Radial'
 'Runflat Tyres' 'Tubeless, Radials' 'Tubeless Radial Tyres' 'Runflat'
 'Tubeless ' 'Tubeless,Runflat' 'Tubeless Radial' 'Tubeless,Radial '
 'Run-Flat' 'Radial ' 'Runflat Tyre' 'Runflat,Radial' 'Tubeless. Runflat'
 'Radial Tubeless' 'Tubeless Tyres All Terrain' 'Radial with tube']

In [133]:
tyr=kolkata["Tyre Type.1"].mode()[0]
kolkata["Tyre Type.1"]=kolkata["Tyre Type.1"].fillna(tyr)
tyr1=LabelEncoder()
kolkata["TyreTypeEncoded"]=tyr1.fit_transform(kolkata["Tyre Type.1"])

In [134]:
kolkata=kolkata.drop(columns=["Tyre Type.1"])

In [135]:
#print(kolkata["Alloy Wheel Size"].unique())
#allo=kolkata["Alloy Wheel Size"].mode()[0]
#kolkata["Alloy Wheel Size"]=kolkata["Alloy Wheel Size"].fillna(allo)

In [136]:
print(kolkata["No Door Numbers.1"].unique())
no=kolkata["No Door Numbers.1"].mean()
kolkata["NoDoorNumbers"]=kolkata["No Door Numbers.1"].fillna(no)

[nan  5.  4.  3.  2.  6.]

In [137]:
kolkata["NoDoorNumbers"]=kolkata["NoDoorNumbers"].astype(int)

In [138]:
print(kolkata["Length"].unique())

['3715mm' '3998mm' '3746mm' '3995mm' '4300mm' '4395mm' '3785mm' '3995 mm'
 '4490 mm' '3765mm' '3955 mm' '4585mm' '4436mm' '3993' '4440mm' '4841mm'
 '3845mm' '4360' '5246mm' '3610 mm' '3565mm' '5063mm' '4701mm' '4405mm'
 '3599mm' '4395 mm' '4686mm' '4936mm' '4695 mm' '3985mm' '4530mm' '4933mm'
 '3445mm' '4430mm' '3850mm' '4315mm' '5075mm' '3495mm' '5120mm' '4661mm'
 '5089mm' '3731mm' '3994mm' '3810mm' '3695mm' '4386mm' '4270mm' '4598mm'
 '3840mm' '4824mm' '4490mm' '3955mm' '4498mm' '4670mm' '3775mm' '3970mm'
 '4413mm' '3675mm' '4708' '3636mm' '3585mm' '3679mm' '4635mm' '4720mm'
 '3610mm' '3620mm' '3991mm' '4390mm' '4425mm' '4655mm' '4500mm' '4234mm'
 '4531mm' '4838mm' '4629mm' '3530mm' '3940 mm' '4892mm' '3886mm' '3700mm'
 '4886mm' '4520mm' '4475mm' '4795mm' '4598 mm' '4656 mm' '4331mm' '3971mm'
 '4575mm' '4549mm' '4660mm' '5091mm' '4329mm' '4265mm' '3999mm' '4384mm'
 '4,560 mm' '4852mm' '4755mm' '4868mm' '4620mm' '4490' '4,140 mm'
 '4922 mm' '4480mm' '4961mm' '3595mm' '4458mm' '4225mm' '4221mm' '4323mm'
 '4250mm' '3545mm' '4359mm' '4375mm' '5115' '4,572 mm' '4861mm' '4560mm'
 '4160mm' '4752 mm' nan '4580mm' '3714mm' '4600mm' '4705mm' '4,580 mm'
 '3990mm' '3995' '3,565 mm' '4440' '4,586 mm' '4277mm' '3565' '4644mm'
 '3429mm' '3655 mm' '4370mm' '5060mm' '3954mm' '4708mm' '4388mm' '3795mm'
 '4915mm' '3992mm' '4699mm' '4726mm' '4731mm' '4292mm' '4803 mm' '3765'
 '4655 mm' '4817mm' '4819mm' '4658mm' '4630mm' '4545mm' '3590mm' '2974'
 '3370mm' '4659mm' '4509mm' '3993mm' '3690mm' '4735mm' '3760mm' '4439mm'
 '4597mm' '4815mm' '3989mm' '3640mm' '3675' '4695mm' '3805mm' '4300 mm'
 '3535 mm' '4735' '4056mm' '4456' '4907mm' '4950mm' '3395mm' '4222mm'
 '4296mm' '4435mm' '5150 mm' '4247mm' '3981mm' '3099 mm' '4838 mm'
 '4788mm' '3801 mm' '4290mm' '4,282 mm' '4657mm' '4833mm' '4859mm'
 '3987mm' '4525mm' '4477mm' '3430mm' '4879mm' '4540mm' '4,838 mm' '4648mm'
 '4305mm' '3099mm  ' '4541mm' '4420 mm' '4585 mm' '4150 mm' '5247mm'
 '4,421 mm' '3988mm' '4596mm' '5067mm' '3435mm' '4282mm' '4891mm' '3445'
 '3,827 mm' '4369mm' '4591mm' '4650mm' '4769mm' '3920mm' '4324mm' '4000mm'
 '4385mm' '4807mm' '4223mm' '4421mm' '4420mm' '4456mm' '4985mm' '5115mm'
 '4300' '3780mm' '4299 mm' '4500' '4618 mm' '4107mm' '4825mm' '3655mm'
 '4371 mm' '4882mm' '4453mm' '4325mm' '4570mm' '4569mm' '3600mm' '3500mm'
 '4637mm' '4,435 mm' '4797mm' '4445mm' '4285 mm' '4697 mm' '4249mm'
 '3801mm' '4424 mm' '5252mm' '4970mm' '4574' '4820mm' '4318mm' '3884mm'
 '3825mm' '4417mm' '4546mm' '4688mm' '4850' '4823' '4765mm' '4,310 mm'
 '5015mm' '3827mm' '4377mm' '4320mm' '4963mm' '3802mm' '3795 mm' '4315'
 '4751mm' '4360mm' '4345mm' '4662mm' '3895mm' '4310mm' '3520 mm' '4470mm'
 '4624mm' '4633mm' '3900mm' '4850mm' '3335mm' '3815mm' '4384 mm' '3996'
 '5238mm' '5255mm' '4,560mm' '5018mm' '5226mm' '5000mm' '4429' '5207mm'
 '5064mm' '4988mm' '4253mm' '4924mm' '4939mm' '4890mm' '5052 mm' '3941 mm'
 '4940mm' '4559mm' '4855mm' '4518mm' '5462 mm' '4455mm' '5130mm' '3520mm'
 '4606 mm' '4819' '4762mm' '4097mm' '3,970 mm' '5010' '4535mm' '4922mm'
 '4685mm' '4447mm' '4691mm' '4963 mm' '4869mm' '4143mm' '3515mm' '5295mm'
 '4365' '4583' '4405' '4365mm' '5179mm' '4709mm' '4656mm' '4665 mm'
 '4682mm' '5206mm' '3695' '4975 mm' '4355mm' '4903mm' '4627mm' '3788mm'
 '4413 mm' '4850 mm' '4693 mm' '4767mm' '4010mm' '4781mm' '4410mm'
 '4800mm' '4561mm' '4291mm' '5200mm' '4628mm' '4569 mm' '4780mm' '4495mm'
 '3825 mm' '4507 mm' '4170mm' '5350mm' '4158 mm' '4673mm' '5215mm'
 '3535mm' '4425 mm' '4,530 mm' '4870mm' '4697mm' '4716' '4017mm' '3731'
 '4749mm' '3880mm' '4180mm' '4690mm' '4,554 mm' '4270 mm' '4095mm'
 '4519mm' '4894mm' '3990']

In [139]:
kolkata["Length"]=kolkata["Length"].str.replace("mm","").str.replace(",","").str.replace(" ","")
kolkata["Length"]=pd.to_numeric(kolkata["Length"])
leng=kolkata["Length"].mean()
kolkata["Length"]=kolkata["Length"].fillna(leng).astype(int)

In [140]:
kolkata["Length"]

0       3715
1       3998
2       3746
3       3995
4       4300
        ...
8326    3775
8327    4315
8328    4100
8329    4100
8330    4100
Name: Length, Length: 8331, dtype: int32

In [141]:
print(kolkata["Width"].unique())

['1635mm' '1765mm' '1647mm' '1660mm' '1785mm' '1818mm' '1770 mm' '1730 mm'
 '1745mm' '1694 mm' '1890mm' '2020mm' '1710mm' '1811' '1695mm' '1846mm'
 '1735' '1822' '2130mm' '1645 mm' '1525mm' '1860mm' '2040mm' '1495mm'
 '1735 mm' '2126mm' '1840 mm' '1734mm' '1775mm' '1874mm' '1515mm' '1817mm'
 '1727mm' '1800mm' '2065mm' '1475mm' '2141mm' '1894mm' '2177mm' '1579mm'
 '1811mm' '1665mm' '1655' '1699mm' '1780mm' '1735mm' '1828mm' '1730mm'
 '1694mm' '1751mm' '1814mm' '1680mm' '1682mm' '1715mm' '2138' '1595mm'
 '2097mm' '1821 mm' '1835mm' '1750' '1550mm' '1790mm' '1819mm' '1822mm'
 '2089mm' '1490' '1710 mm' '1690mm' '1739' '1938mm' '1850mm' '1855mm'
 '1894 mm' '1729mm' '1890 mm' '2000mm' '1820mm' '1992mm' '1760mm' '1902mm'
 '1813mm' '1,730 mm' '1900mm' '1854mm' '1776mm' '1730' '1,634 mm'
 '2218 mm' '1877mm' '1796mm' '1809mm' '1670mm' '2010mm' '1700mm' '1985'
 '1,769 mm' '1864mm' '1918 mm' nan '1770mm' '1683mm' '2173mm' '1840mm'
 '1,770 mm' '2034mm' '1745' '1790' '1,595 mm' '1695' '1,772 mm' '1740mm'
 '1520' '1778mm' '1560mm' '1704mm' '1620 mm' '1579' '1811 mm' '1788mm'
 '1737mm' '1891mm' '2019mm' '2086mm' '1600mm' '1677mm' '1842mm' '1748mm'
 '2175mm' '1831mm' '1758' '1765 mm' '1677' '1965 mm' '1777 mm' '1575mm'
 '1505' '1758mm' '1410mm' '1839mm' '1755' '1830mm' '1821mm' '1687mm'
 '1475' '2099mm' '1680' '1695 mm' '1495 mm' '1830' '2195mm' '1694'
 '1608mm' '1820' '2102mm' '1706mm' '1640mm' '1845mm' '1490mm' '1793mm'
 '2075mm' '1733mm' '1703mm' '1817 mm' '1665 mm' '1,686 mm' '1670' '1725mm'
 '2058mm' '2071mm' '1,817 mm' '2098mm' '1739mm' '1752mm' '1866 mm'
 '2110mm' '1642mm' '1,780 mm' '1620mm' '2091mm' '1574mm' '1686mm' '2129mm'
 '1515' '1,620 mm' '1918mm' '1859mm' '1726mm' '1984mm' '2112mm' '1960mm'
 '2047mm' '2184mm' '1926mm' '1785' '1734' '2220mm' '1822 mm' '1813 mm'
 '1825mm' '1996 mm' '1750mm' '1662mm' '1769mm' '2120mm' '1,680 mm'
 '2145mm' '1,726 mm' '1923 mm' '1795mm' '2041mm' '1804 mm' '2105mm'
 '1931mm' '1863' '1748' '1805mm' '1804mm' '1939mm' '1775' '1902 mm' '1960'
 '2032mm' '1866mm' '1827' '2100mm' '1,710 mm' '1742' '1764mm' '1898mm'
 '1800' '2033' '1795' '1917' '2042mm' '2031mm' '2015mm' '1690' '2022mm'
 '1826mm' '1660' '1440mm' '1727' '1965mm' '1,730mm' '1815mm' '2138mm'
 '1871mm' '1895mm' '2157mm' '1970mm' '1645mm' '2212 mm' '1704 mm' '2212mm'
 '1729' '2130 mm' '1976 mm' '1847mm' '1705mm' '1789mm' '1,682 mm' '1850'
 '2218mm' '1980mm' '2060mm' '2158mm' '2019 mm' '2006mm' '1810mm' '1699 mm'
 '2033mm' '1818' '2133mm' '1827mm' '1799 mm' '1800 mm' '1893mm' '1872mm'
 '1636mm' '1865 mm' '1869mm' '1888mm' '1703 mm' '1960 mm' '1832mm'
 '1540mm' '1911mm' '2170mm' '1722mm' '1769 mm' '1865mm' '2140mm' '1731 mm'
 '2096mm' '1625 mm' '1849mm' '1,705 mm' '1882mm' '1897' '1880mm'
 '1,781 mm' '1690 mm' '2090mm' '1852mm' '1815 mm' '1698mm']

In [142]:
kolkata["Width"]=kolkata["Width"].str.replace("mm","").str.replace(",","").str.replace(" ","")
kolkata["Width"]=pd.to_numeric(kolkata["Width"])
wid=kolkata["Width"].mean()
kolkata["Width"]=kolkata["Width"].fillna(wid).astype(int)

In [143]:
print(kolkata["Width"].unique())

[1635 1765 1647 1660 1785 1818 1770 1730 1745 1694 1890 2020 1710 1811
 1695 1846 1735 1822 2130 1645 1525 1860 2040 1495 2126 1840 1734 1775
 1874 1515 1817 1727 1800 2065 1475 2141 1894 2177 1579 1665 1655 1699
 1780 1828 1751 1814 1680 1682 1715 2138 1595 2097 1821 1835 1750 1550
 1790 1819 2089 1490 1690 1739 1938 1850 1855 1729 2000 1820 1992 1760
 1902 1813 1900 1854 1776 1634 2218 1877 1796 1809 1670 2010 1700 1985
 1769 1864 1918 1728 1683 2173 2034 1772 1740 1520 1778 1560 1704 1620
 1788 1737 1891 2019 2086 1600 1677 1842 1748 2175 1831 1758 1965 1777
 1575 1505 1410 1839 1755 1830 1687 2099 2195 1608 2102 1706 1640 1845
 1793 2075 1733 1703 1686 1725 2058 2071 2098 1752 1866 2110 1642 2091
 1574 2129 1859 1726 1984 2112 1960 2047 2184 1926 2220 1825 1996 1662
 2120 2145 1923 1795 2041 1804 2105 1931 1863 1805 1939 2032 1827 2100
 1742 1764 1898 2033 1917 2042 2031 2015 2022 1826 1440 1815 1871 1895
 2157 1970 2212 1976 1847 1705 1789 1980 2060 2158 2006 1810 2133 1799
 1893 1872 1636 1865 1869 1888 1832 1540 1911 2170 1722 2140 1731 2096
 1625 1849 1882 1897 1880 1781 2090 1852 1698]

In [144]:
print(kolkata["Height"].unique())

['1565mm' '1647mm' '1535mm' '1520mm' '1595mm' '1640mm' '1490mm' '1605 mm'
 '1485 mm' '1510mm' '1544 mm' '1785mm' '1611mm' '1505mm' '1606' '1495mm'
 '1468mm' '1530' '1695' '1494mm' '1560 mm' '1590mm' '1427mm' '1700mm'
 '1690 mm' '1442mm' '1466mm' '1850 mm' '1470mm' '1455mm' '1475mm' '1975mm'
 '1414mm' '1645mm' '1460mm' '1850mm' '1786mm' '1737mm' '1474mm' '1607mm'
 '1515mm' '1555' '1630mm' '1706mm' '1530mm' '1508mm' '1485mm' '1544mm'
 '1697mm' '1476mm' '1620mm' '1453mm' '1655mm' '1676' '1670mm' '1550mm'
 '1478mm' '1484mm' '1627 mm' '1760mm' '1500mm' '1605' '1467mm' '1675mm'
 '1665mm' '1635mm' '1573mm' '1421mm' '1482mm' '1695mm' '1520' '1505 mm'
 '1837mm' '1525mm' '1643' '1762mm' '1660mm' '1835mm' '1706 mm' '1639 mm'
 '1671mm' '1469mm' '1680mm' '1446mm' '1538mm' '1626 mm' '1515' '1685mm'
 '1708mm' '1,487 mm' '1555mm' '1483mm' '1601mm' '1840mm' '1471mm' '1485'
 '1,379 mm' '1745 mm' '1416mm' '1612mm' '1650mm' '1370mm' '1490' '1390mm'
 '1557mm' '1755' '1,485 mm' '1487mm' '1621 mm' nan '1755mm' '1407mm'
 '1724mm' '1,755 mm' '1617mm' '1652mm' '1500' '1642' '1,550 mm' '1495'
 '1,427 mm' '1540mm' '1567' '1541mm' '1675 mm' '1429 mm' '1826mm' '1570mm'
 '1676mm' '1608mm' '1560mm' '1537mm' '1429mm' '1489mm' '1651mm' '1433mm'
 '1572' '1489 mm' '1535' '1922 mm' '1796mm' '1644mm' '1640' '1844mm'
 '1432mm' '1585mm' '1465mm' '1572mm' '1523' '1616mm' '1795mm' '1606mm'
 '1477mm' '1480mm' '1825' '1710mm' '1490 mm' '1627mm' '1405 mm' '1795'
 '1880mm' '1740mm' '1544' '1420mm' '1855mm' '1995' '1895mm' '1464mm'
 '1904mm' '1691mm' '1690' '1518mm' '1765mm' '1805 mm' '1534mm' '1586mm'
 '1620 mm' '1501mm' '1482 mm' '1619mm' '1530 mm' '1430mm' '1,468 mm'
 '1678mm' '1855' '1450mm' '1545mm' '1,462 mm' '1661mm' '1750mm' '1674mm'
 '1643mm' '1507mm' '1480 mm' '1774 mm' '1540 mm' '1448mm' '1513mm'
 '1,940 mm' '1474' '1447mm' '1457mm' '1546mm' '1532' '1719mm' '1475'
 '1,440 mm' '1977mm' '1925mm' '1698mm' '1930mm' '1522mm' '1784mm' '1409mm'
 '1867mm' '1564' '1595' '1905mm' '1601' '1803mm' '1557 mm' '1675'
 '1488 mm' '1649 mm' '1848mm' '1666mm' '1593mm' '1539mm' '1713mm'
 '1,765 mm' '1995mm' '1,976 mm' '1624 mm' '1655' '1503mm' '1817mm'
 '1418mm' '1652' '1489' '1548mm' '1600mm' '1498-1501' '1288mm' '1505'
 '1658mm' '1845' '1685' '1774mm' '1441' '1,505 mm' '1615' '1486mm'
 '1653mm' '1497mm' '1603mm' '1537' '1550 mm' '1645' '1437' '1857' '1308mm'
 '1800mm' '1393mm' '1690mm' '1405mm' '1656 mm' '1642mm' '1432' '1922mm'
 '1479mm' '1,487mm' '1621mm' '1967mm' '1598' '1823mm' '1703mm' '1435mm'
 '1720mm' '1441mm' '1888mm' '1772mm' '1740 mm' '1525 mm' '1411mm' '1705mm'
 '1498mm' '1558mm' '1498 mm' '1624mm' '1969 mm' '1415mm' '1653 mm'
 '1561mm' '1,453 mm' '1950' '1745mm' '1838mm' '1945mm' '1598mm' '1443 mm'
 '1303mm' '1466 mm' '1437mm' '1445mm' '1639mm' '1433 mm' '1720 mm'
 '1473mm' '1545' '1445 mm' '1669 mm' '1845 mm' '1402 mm' '1456mm' '1875mm'
 '1468 mm' '1779mm' '1496mm' '1868mm' '1542mm' '1780mm' '1776mm' '1455 mm'
 '1562mm' '1649mm' '1810mm' '1575 mm' '1865mm' '1880 mm' '1,490 mm' '1669'
 '1900mm' '1,459 mm' '1395 mm' '1395mm' '1300mm' '1369mm' '1840 mm' '1549']

In [145]:
kolkata["Height"]
kolkata["Height"]=kolkata["Height"].str.replace("mm","").str.replace(",","").str.replace(" ","").str.replace("-","")
kolkata["Height"]=pd.to_numeric(kolkata["Height"])
hei=kolkata["Height"].mean()
kolkata["Height"]=kolkata["Height"].fillna(hei).astype(int)

In [146]:
print(kolkata["Wheel Base"].unique())

['2425mm' '2519mm' '2400mm' '2600mm' '2636mm' '2450mm' '2500 mm' '2650 mm'
 '2520mm' '2530 mm' '2700mm' '2729mm' '2525mm' '2498' '2888mm' '2450'
 '2673' '3165mm' '2400 mm' '2380mm' '3079mm' '2808mm' '2740 mm' '2840mm'
 '2975mm' '2750 mm' '2570mm' '2912mm' '2360mm' '2680mm' '2495mm' '2610mm'
 '3075mm' '2741mm' '3002mm' '2422mm' '2498mm' '2455mm' '2435' '2552mm'
 '2590mm' '2920 mm' '2650mm' '2530mm' '2810mm' '2688mm' '2580mm' '2550mm'
 '2456mm' '2385mm' '2864' '2776mm' '2600 mm' '2750mm' '2345mm' '2500'
 '2553mm' '2760mm' '2761mm' '2673mm' '2807mm' '2380' '2,525 mm' '2850mm'
 '2491mm' '2435mm' nan '2933mm' '2670mm' '2745' '2741 mm' '2873 mm'
 '2469mm' '2620mm' '3070mm' '2500mm' '2740mm' '2854mm' '2555mm' '2835mm'
 '2874mm' '2650' '2430mm' '2,486 mm' '2975 mm' '2909mm' '2470mm' '2637mm'
 '2651mm' '2585mm' '2440mm' '2699mm' '3060' '2,578 mm' '2841mm' '2390mm'
 '2864 mm' '2467mm' '2,750 mm' '2702mm' '2520' '2,380 mm' '2600'
 '2,642 mm' '2630mm' '2633mm' '2348mm' '2490mm' '2435 mm' '2810 mm'
 '2860mm' '2864mm' '2603mm' '2489mm' '2820mm' '2803 mm' '2400' '2915mm'
 '2873mm' '2258mm' '2010' '1840mm' '2648mm' '2679mm' '2501' '2685mm'
 '2775mm' '2510mm' '2375mm' '2350' '2730mm' '2335 mm' '2750' '2660mm'
 '2530' '2443mm' '2680' '2968mm' '2800mm' '2578mm' '2740' '3105 mm'
 '2540mm' '2230 mm' '2761 mm' '2450 mm' '3014' '2780mm' '2,761 mm'
 '2720mm' '2230mm' '2787mm' '2550 mm' '2405mm' '2760 mm' '3157mm' '2462mm'
 '2,550 mm' '2960mm' '2486mm' '2360' '2,373 mm' '2794mm' '2782mm' '2690mm'
 '2465mm' '2745m' '2857mm' '2595mm' '2920mm' '2950mm' '3060mm' '2555'
 '2923mm' '2760' '2703 mm' '2681mm' '2525 mm' '3008mm' '2662mm' '2464mm'
 '2774mm' '2,685 mm' '2,400 mm' '2385' '2647mm' '2699 mm' '2795mm'
 '2593mm' '2460mm' '2470' '2580' '2865mm' '2865' '2825mm' '2,480 mm'
 '2445' '2652mm' '2470 mm' '2610' '2610m' '2622mm' '2350mm' '2745mm'
 '2425' '2175mm' '2673 mm' '3210mm' '2845mm' '2,603mm' '3022mm' '2790mm'
 '3135mm' '2999mm' '2939mm' '2922mm' '2995mm' '2930mm' '2994 mm' '2490 mm'
 '2895mm' '3365 mm' '2961' '2819mm' '2961mm' '2,456 mm' '3000' '2941 mm'
 '2430 mm' '2651' '3095mm' '2640mm' '2430' '2636' '3128mm' '2700 mm'
 '2670 mm' '2870mm' '2520 mm' '2865 mm' '2786mm' '3120mm' '2578 mm'
 '2776 mm' '2984mm' '2512 mm' '2711mm' '3150mm' '2705mm' '3264mm' '2335mm'
 '2,600 mm' '2791mm' '2725mm' '2465 mm' '2480mm' '2575 mm' '2365mm'
 '2855mm' '2800 mm']

In [147]:
kolkata["Wheel Base"]
kolkata["Wheel Base"]=kolkata["Wheel Base"].str.replace("mm","").str.replace(",","").str.replace(" ","").str.replace("m","")
kolkata["Wheel Base"]=pd.to_numeric(kolkata["Wheel Base"])
whe=kolkata["Wheel Base"].mean()
kolkata["Wheel Base"]=kolkata["Wheel Base"].fillna(whe).astype(int)

In [148]:
print(kolkata["Front Tread"].unique())

['1420mm' nan '1400mm' '1479mm' '1440mm' '1515mm' '1617mm' '1505mm'
 '1480mm' '1558mm' '1530' '1560' '1624mm' '1463 mm' '1315mm' '1595mm'
 '1564mm' '1295mm' '1510 mm' '1588mm' '1605mm' '1540 mm' '1569mm' '1627mm'
 '1501mm' '1655mm' '1651mm' '1450mm' '1430' '1530mm' '1541 mm' '1495mm'
 '1490mm' '1539mm' '1470mm' '1463mm' '1536' '1386mm' '1457mm' '1546mm'
 '1460mm' '1560mm' '1,505 mm' '1475mm' '1492mm' '1527' '1644mm' '1621 mm'
 '1565mm' '1510mm' '1615mm' '1519mm' '1577mm' '1585mm' '1485mm' '1666 mm'
 '1559mm' '1555mm' '1531' '1520mm' '1435mm' '1552mm' '1520' '1,539 mm'
 '1620 mm' '1600mm' '1621mm' '1540mm' '1601mm' '1,400 mm' '1490'
 '1,522 mm' '1316' '1470 mm' '1547' '1544 mm' '1620mm' '1571mm' '1544mm'
 '1572mm' '1496mm' '1641mm' '1553mm' '1521 mm' '1648mm' '1549mm' '1205mm'
 '1535mm' '1576mm' '1561mm' '1580mm' '1280' '1540' '1387mm' '1314mm'
 '1500mm' '1476' '1325 mm' '1545 mm' '1,474 mm' '1616mm' '1443' '1598mm'
 '1547mm' '1380 mm' '1380mm' '1,496 mm' '1541mm' '1474mm' '1665mm' '1295'
 '1415 mm' '1445mm' '1634mm' '1543mm' '1690mm' '1463' '1534mm' '1626mm'
 '1505 mm' '1476 mm' '1408mm' '1405mm' '1619mm' '1632mm' '1,445 mm'
 '1641 mm' '1590mm' '1517mm' '1529mm' '1569 mm' '1440' '1591mm' '1680mm'
 '1484mm' '1,450 mm' '1606mm' '1597mm' '1280mm' '1618mm' '1570mm' '1639mm'
 '1640mm' '1705mm' '1395 mm' '1689mm' '1679 mm' '1594mm' '1634 mm'
 '1568mm' '1501 mm' '1,463 mm' '1666mm' '1628mm' '1376mm' '1485' '1605 mm'
 '1589mm' '1602mm' '1586mm' '1300mm' '1511mm' '1473mm' '1496' '1668mm'
 '1513 mm' '1522mm' '1355 mm' '1,480 mm' '1465mm' '1534 mm' '1450 mm'
 '1365mm' '1520 mm']

In [149]:
kolkata["Front Tread"]
kolkata["Front Tread"]=kolkata["Front Tread"].str.replace("mm","").str.replace(",","").str.replace(" ","")
kolkata["Front Tread"]=pd.to_numeric(kolkata["Front Tread"])
fro=kolkata["Front Tread"].mean()
kolkata["Front Tread"]=kolkata["Front Tread"].fillna(fro).astype(int)

In [150]:
kolkata["Rear Tread"]
kolkata["Rear Tread"]=kolkata["Rear Tread"].str.replace("mm","").str.replace(",","").str.replace(" ","").str.replace("`","")
kolkata["Rear Tread"]=pd.to_numeric(kolkata["Rear Tread"])
fro=kolkata["Rear Tread"].mean()
kolkata["Rear Tread"]=kolkata["Rear Tread"].fillna(fro).astype(int)

In [151]:

kolkata["Kerb Weight"]=kolkata["Kerb Weight"].str.replace("Kg","").str.replace("kg","").str.replace("kgs","").str.replace("-","").str.replace(" ","").str.replace(",","").str.replace("s","")
kolkata["Kerb Weight"]=pd.to_numeric(kolkata["Kerb Weight"])
kerb=kolkata["Kerb Weight"].mean()
kolkata["Kerb Weight"]=kolkata["Kerb Weight"].fillna(kerb).astype(int)

In [152]:
#print(kolkata["Gross Weight"])
#kolkata["Gross Weight"]=kolkata["Gross Weight"].str.replace("mm","").str.replace("Kg","").str.replace("kg","").str.replace("kgs","").str.replace("-","").str.replace(" ","").str.replace(",","").str.replace("s","")
#kolkata["Gross Weight"]=pd.to_numeric(kolkata["Gross Weight"])
#gros=kolkata["Gross Weight"].mean()
#kolkata["Gross Weight"]=kolkata["Gross Weight"].fillna(gros).astype(int)

In [153]:
#print(kolkata["Ground Clearance Unladen"].unique())
#kolkata["Ground Clearance Unladen"]=kolkata["Ground Clearance Unladen"].str.replace("mm","").str.replace(" ","")
#kolkata["Ground Clearance Unladen"]=pd.to_numeric(kolkata["Ground Clearance Unladen"])
#grou=kolkata["Ground Clearance Unladen"].mean()
#kolkata["Ground Clearance Unladen"]=kolkata["Ground Clearance Unladen"].fillna(grou).astype(int)

In [154]:
#kolkata=kolkata.drop(columns=["Seating Capacity.1"])
#kolkata=kolkata.drop(columns=["Steering Type"])
#kolkata=kolkata.drop(columns=["Tyre Type.1"])
#kolkata=kolkata.drop(columns=["Alloy Wheel Size.1"])
#kolkata=kolkata.drop(columns=["No Door Numbers.1"])

#kolkata=kolkata.drop(columns=["Seating Capacity.2"])
#kolkata=kolkata.drop(columns=["Steering Type.2"])
#kolkata=kolkata.drop(columns=["Tyre Type.2"])

In [155]:
kolkata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8331 entries, 0 to 8330
Data columns (total 55 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   bt                         8331 non-null   object
 1   km                         8331 non-null   int32
 2   transmission               8331 non-null   object
 3   ownerNo                    8331 non-null   int64
 4   owner                      8331 non-null   object
 5   modelYear                  8331 non-null   int64
 6   centralVariantId           8331 non-null   int64
 7   price                      8331 non-null   float64
 8   trendingText               8331 non-null   object
 9   Registration Year          8331 non-null   int32
 10  Fuel Type                  8331 non-null   object
 11  Seats                      8331 non-null   int32
 12  Kms Driven                 8331 non-null   int32
 13  RTO                        8331 non-null   int32
 14  Ownership                  8331 non-null   int64
 15  Engine Displacement        8331 non-null   int32
 16  Year of Manufacture        8331 non-null   int32
 17  Mileage                    8331 non-null   int32
 18  Wheel Size                 8331 non-null   float64
 19  Engine Type                8331 non-null   int32
 20  No of Cylinder             8295 non-null   float64
 21  Values per Cylinder        8331 non-null   int32
 22  Turbo Charger              8331 non-null   int32
 23  Super Charger              8331 non-null   int64
 24  Length                     8331 non-null   int32
 25  Width                      8331 non-null   int32
 26  Height                     8331 non-null   int32
 27  Wheel Base                 8331 non-null   int32
 28  Front Tread                8331 non-null   int32
 29  Rear Tread                 8331 non-null   int32
 30  Kerb Weight                8331 non-null   int32
 31  No Door Numbers.1          5355 non-null   float64
 32  Gear Box                   5651 non-null   object
 33  Drive Type                 4582 non-null   object
 34  Turning Radius             4646 non-null   object
 35  Front Brake Type           5666 non-null   object
 36  Rear Brake Type            5666 non-null   object
 37  Cargo Volumn               6670 non-null   object
 38  city                       8331 non-null   object
 39  car_names_encoded          8331 non-null   int32
 40  Model_encoded              8331 non-null   int32
 41  variantName_encoded        8331 non-null   int32
 42  InsuranceValidity          8331 non-null   int32
 43  MaxPower_rpm               8331 non-null   int32
 44  MaxPowerbhp                8331 non-null   float64
 45  TorqueNm                   8331 non-null   float64
 46  ColorEncoded               8331 non-null   int32
 47  Torque_rpm                 8331 non-null   int32
 48  NoOfCylinder               8331 non-null   int32
 49  ValueConfigurationEncoded  8331 non-null   int32
 50  Fuel Suppy System encoded  8331 non-null   int32
 51  SeatingCapacityEncoded     8331 non-null   int64
 52  SteeringTypeEncoded        8331 non-null   int32
 53  TyreTypeEncoded            8331 non-null   int32
 54  NoDoorNumbers              8331 non-null   int32
dtypes: float64(6), int32(31), int64(6), object(12)
memory usage: 2.5+ MB

In [156]:
kolkata["Gear Box"]

0       5 Speed
1        5 Speed
2        5 Speed
3       5 Speed
4        5 Speed
          ...
8326     6 Speed
8327         NaN
8328         NaN
8329         NaN
8330         NaN
Name: Gear Box, Length: 8331, dtype: object

In [157]:
print(kolkata["Gear Box"].unique())

['5 Speed ' '5 Speed' '6 Speed' '7-Speed' '4 Speed' '6 Speed ' '8G-DCT'
 '5-Speed' '7 Speed' '9 Speed' '8 Speed' '8-Speed Steptronic' '6-Speed'
 '7-Speed DCT' '9-Speed' '8 Speed Tiptronic' '5' '6 Speed IMT'
 '6-speed AutoSHIFT' '6-speed CVT' 'CVT' '6-speed' '7-speed DCT'
 '7 Speed DSG' '7 Speed DCT' '6' '8-Speed' '5-speed' '6 speed '
 '8-Speed Steptronic Sport Automatic Transmission' '5 speed' '7 Speed CVT'
 'Five Speed Manual' '5 Speed CVT' nan '6 Speed AT' '6-Speed iMT'
 '6-Speed DCT' '7-Speed S-Tronic '
 '7G DCT 7-Speed Dual Clutch Transmission ' '7-Speed S-Tronic' '5-Speed`'
 '9 speed Tronic' '6-Speed IVT' 'Direct Drive' '6 Speed IVT' 'IVT'
 '8 Speed CVT' 'Five Speed Manual Transmission'
 '5 Speed AT+ Paddle Shifters' '8-Speed ' 'iMT' 'AGS' '6Speed' '4-Speed'
 '6-Speed IMT' '6 Speed MT' '9-speed automatic' '5 speed manual'
 '9 -speed' '8' '8 speed' '6-speed DCT' '8-speed' '7-speed Stronic'
 '7 Speed 7G-DCT' '4 Speed ' 'Mercedes Benz 7 Speed Automatic'
 '8 Speed Sport' '8-speed tiptronic' '7-Speed S tronic'
 '8-Speed Automatic Transmission' '9G TRONIC' 'eCVT' 'Single Speed'
 '6 Speed with Sequential Shift' '8 Speed ' '6-speed IVT'
 'Five Speed Manual Transmission Gearbox'
 'Six Speed Manual with Paddle Shifter' '6-Speed AT' '6-speed iMT'
 '7-Speed DSG' '7 speed' '6 speed automatic' '7G-DCT'
 'Six Speed Geartronic, Six Speed Automati'
 '5 Speed Manual (Cable Type Gear Shift)' 'Six Speed Automatic Gearbox'
 '10 Speed' 'Fully Automatic' 'Single-speed transmission'
 'Six Speed  Gearbox' '5 Speed Forward, 1 Reverse' '7 Speed S tronic']

In [158]:
gear=kolkata["Gear Box"].mode()[0]
kolkata["Gear Box"]=kolkata["Gear Box"].fillna(gear)

In [159]:
#kolkata=kolkata.drop(columns=["Gear Box"])

In [160]:
print(kolkata["Drive Type"].unique())

['FWD' 'FWD ' '4X2' 'AWD' nan 'RWD' '4x2' '2WD' '4WD' '2 WD'
 'Front Wheel Drive' 'Rear Wheel Drive with ESP' '4X4' 'Two Wheel Drive'
 '2WD ' 'Permanent all-wheel drive quattro' 'RWD(with MTT)' '4x4'
 'All Wheel Drive']

In [161]:

dri=kolkata["Drive Type"].mode()[0]
kolkata["Drive Type"]=kolkata["Drive Type"].fillna(dri)
drive=LabelEncoder()
kolkata["DriveTypeEncoded"]=drive.fit_transform(kolkata["Drive Type"])

In [162]:
kolkata=kolkata.drop(columns=["Drive Type"])

In [163]:
print(kolkata["Turning Radius"].unique())

['4.7 metres' '5.3 metres' '4.9 meters' '5.2 meters' nan '4.6 metres'
 '5.4 metres' '4.8 metres' '5.1 meters' '5.6 metres' '5.1' '4.8' '5.2m'
 '6.15 metres ' '4.4 meters' '6 metres' '5.8 metres' '5.2 metres'
 '5.61 metres' '5.6' '5.9 m' '5.95 metres' '4.6' '4.6m' '6.2 metres'
 '6.0 metres' '4.9 metres' '5.1m' '5 m' '4.8 Meters' '5.5 metres'
 '5.55 metres' '5.3metres' '4.97 metres' '5.3 meters' '5.05 metres'
 '5.65 metres' '5.3 m' '4.5 metres' '4.9' '4.6metres' '5.55' '4.5'
 '5.20 m' '4.7 m' '6.4 meters' '5.8' '5.9metres' '5.2meters' '5.5 m'
 '5.7 metres' '5.4' '4.9 m' '5.75 metres' '5.35 metres' '5.05' '5.0metres'
 '5.4 m' '5.5m' '4.7m' '5.2' '5.05 meters' '4.85' '5.3' '5.55 m'
 '5.25 metres' '5.0m' '5.9 metres' '5.0' '4.8metres' '4.7 Metre'
 '5.9 meters' '4.35mm' '4.2' '4.9metres' '4.1 m' '5.39' '5.4 meters'
 '5.4m' '5.52 metres' '5 metres' '4.85metres' '4.5metres' '5.35m'
 '4.9 meter' '5.6 meters' '5.1 metres' '6.28 metres' '5.6metres'
 '5.0 metres' '5.25 m' '5.1 meter' '4.98' '4 m' '5.2 mtrs.' '5.1metres'
 '5.75m' '4.65 metres' '5.1 m' '5m' '4.0 metres' '4.9m' '5.25 meters'
 '5.0 m' '6.35m' '5.42 m' '5.20 mtrs.' '5.42 metres' '5.2metres' '5.7m'
 '5.45 metres' '6.15 metres' '5.5' '6.05 meters' '4.65metres' '4.7' '4.4m'
 '5.4 meter' '5.65 meters' '5.8 meters' '5.62 m' '5.15 metres '
 '5.15 metres' '5.92 metres' '5.9 metres ' '4.85 metres ' '11.4m' '5.25'
 '11.6m' '5.03 m' '4.65 M' '5.4metres' '5.5metres' '4.7metres'
 '11.6 metres' '5.35' '11.5 metres' '5.05 m' '4.6 m' '5.45 metres ' '5.6m'
 '4.9 Meters' '4.4metres' '5.3 Meter' '6.05 metres' '4.85 metres'
 '12.40 m' '5.85 meters' '5.85 metres' '5 meters' '5.8 m' '5.5 meters'
 '6.1 m' '4.58metres' '5.46 m' '6.1 metres' '5.6 m' '5.25mm' '6250mm'
 '13m' '5.2 m' '4.6 metres ']

In [164]:

kolkata["Turning Radius"]=kolkata["Turning Radius"].str.replace("meter","").str.replace("m","").str.replace("etres","").str.replace("meters","").str.replace("m","").str.replace(" ","").str.replace("metres","").str.replace("s","").str.replace("M","").str.replace("eter","").str.replace("etre","").str.replace("tr","").str.rstrip(".")
kolkata["Turning Radius"]=pd.to_numeric(kolkata["Turning Radius"])
rad=kolkata["Turning Radius"].mean()
kolkata["Turning Radius"]=kolkata["Turning Radius"].fillna(rad).astype(int)

In [165]:
print(kolkata["Front Brake Type"].unique())
bra=kolkata["Front Brake Type"].mode()[0]
kolkata["Front Brake Type"]=kolkata["Front Brake Type"].fillna(bra)
type=LabelEncoder()
kolkata["Front Brake Type"]=type.fit_transform(kolkata["Front Brake Type"])

['Ventilated Disc' 'Disc' 'Disc ' ' Disc' 'Disc & Caliper Type'
 'Ventilated discs' 'Ventilated Discs' 'Ventilated Disc ' nan
 'ventilated Disc' 'Disc, 236 mm' 'Multilateral Disc' 'Solid Disc' 'Disk'
 'Drum' 'Electric Parking Brake' 'Ventilated DIsc' ' Ventilated Disc'
 'Tandem master cylinder with Servo assist' 'Caliper Ventilated Disc'
 'Vantilated Disc' 'Ventilated Disk' 'Ventillated Disc' 'Disc brakes'
 'Mechanical-hydraulic dual circuit' 'disc' 'ventilated disc'
 'Ventlated Disc' 'Ventilated disc']

In [166]:
print(kolkata["Rear Brake Type"].unique())
rea=kolkata["Rear Brake Type"].mode()[0]
kolkata["Rear Brake Type"]=kolkata["Rear Brake Type"].fillna(rea)
type=LabelEncoder()
kolkata["Rear Brake Type"]=type.fit_transform(kolkata["Rear Brake Type"])

['Drum' 'Solid Disc' 'Discs' 'Disc & Caliper Type' 'Disc'
 'Ventilated discs' 'Ventilated Disc' 'Leading-Trailing Drum'
 'ventilated disc' 'self adjusting drums' nan 'Self Adjusting Drum'
 'Drums 180 mm' 'Drums' 'Self-Adjusting Drum' 'Ventilated Discs'
 'Electric Parking Brake' '228.6 mm dia, drums on rear wheels'
 'Solid Disc ' 'Leading & Trailing Drum' 'Drum ' 'Self Adjusting Drums'
 'Disc & Drum' 'Mechanical-hydraulic dual circuit' 'Drum in Discs'
 'Ventialte Disc' 'disc' 'Disc ' 'Drum`']

In [167]:

#kolkata["Top Speed"]=kolkata["Top Speed"].str.replace("/Hour","").str.replace("km/h","").str.replace("Km","").str.replace("Kmph","").str.replace("kmph","").str.replace("km/hr","").str.replace("meters","").str.replace(" ","").str.replace("eter","")
#kolkata["Top Speed"]=pd.to_numeric(kolkata["Top Speed"],errors="coerce")
#top=kolkata["Top Speed"].mean()
#kolkata["Top Speed"]=kolkata["Top Speed"].fillna(top)

In [168]:
#kolkata["Top Speed"]=kolkata["Top Speed"].astype(int)

In [169]:
#kolkata["Acceleration"]=kolkata["Acceleration"].str.replace("Seconds","").str.replace("Sec","").str.replace("sec","").str.replace("s","").str.replace("m","").str.replace(" ","").str.replace("ond","").str.replace("c","")#.str.replace("eter","")
#kolkata["Acceleration"]=pd.to_numeric(kolkata["Acceleration"])
#top=kolkata["Acceleration"].mean()
#kolkata["Acceleration"]=kolkata["Acceleration"].fillna(top)

In [170]:

kolkata["Cargo Volumn"]=kolkata["Cargo Volumn"].str.replace("(3rd Row Folded)","").str.replace("-","").str.replace("liters","").str.replace("L","").str.replace("m","").str.replace(" ","").str.replace("/","").str.replace("litres","").str.replace("itres","")
kolkata["Cargo Volumn"]=kolkata["Cargo Volumn"].str.replace("it","").str.replace("itre","").str.replace("iters","").str.replace("iter","").str.replace("lts","").str.replace("trs","").str.replace("ls","").str.replace("ers","").str.replace("lrs","").str.replace("re","").str.replace("er","")
kolkata["Cargo Volumn"]=pd.to_numeric(kolkata["Cargo Volumn"],errors="coerce")
top=kolkata["Cargo Volumn"].mean()
kolkata["CargoVolumnlr"]=kolkata["Cargo Volumn"].fillna(top)

In [171]:
print(kolkata["Gear Box"].unique())

['5 Speed ' '5 Speed' '6 Speed' '7-Speed' '4 Speed' '6 Speed ' '8G-DCT'
 '5-Speed' '7 Speed' '9 Speed' '8 Speed' '8-Speed Steptronic' '6-Speed'
 '7-Speed DCT' '9-Speed' '8 Speed Tiptronic' '5' '6 Speed IMT'
 '6-speed AutoSHIFT' '6-speed CVT' 'CVT' '6-speed' '7-speed DCT'
 '7 Speed DSG' '7 Speed DCT' '6' '8-Speed' '5-speed' '6 speed '
 '8-Speed Steptronic Sport Automatic Transmission' '5 speed' '7 Speed CVT'
 'Five Speed Manual' '5 Speed CVT' '6 Speed AT' '6-Speed iMT'
 '6-Speed DCT' '7-Speed S-Tronic '
 '7G DCT 7-Speed Dual Clutch Transmission ' '7-Speed S-Tronic' '5-Speed`'
 '9 speed Tronic' '6-Speed IVT' 'Direct Drive' '6 Speed IVT' 'IVT'
 '8 Speed CVT' 'Five Speed Manual Transmission'
 '5 Speed AT+ Paddle Shifters' '8-Speed ' 'iMT' 'AGS' '6Speed' '4-Speed'
 '6-Speed IMT' '6 Speed MT' '9-speed automatic' '5 speed manual'
 '9 -speed' '8' '8 speed' '6-speed DCT' '8-speed' '7-speed Stronic'
 '7 Speed 7G-DCT' '4 Speed ' 'Mercedes Benz 7 Speed Automatic'
 '8 Speed Sport' '8-speed tiptronic' '7-Speed S tronic'
 '8-Speed Automatic Transmission' '9G TRONIC' 'eCVT' 'Single Speed'
 '6 Speed with Sequential Shift' '8 Speed ' '6-speed IVT'
 'Five Speed Manual Transmission Gearbox'
 'Six Speed Manual with Paddle Shifter' '6-Speed AT' '6-speed iMT'
 '7-Speed DSG' '7 speed' '6 speed automatic' '7G-DCT'
 'Six Speed Geartronic, Six Speed Automati'
 '5 Speed Manual (Cable Type Gear Shift)' 'Six Speed Automatic Gearbox'
 '10 Speed' 'Fully Automatic' 'Single-speed transmission'
 'Six Speed  Gearbox' '5 Speed Forward, 1 Reverse' '7 Speed S tronic']

In [172]:
import re

In [174]:
# Clean the "Gear Box" column
tops=kolkata["Gear Box"].mode()[0]
kolkata["Gear Box"] = kolkata["Gear Box"].str.extract(r"^(\d+)", expand=False)
kolkata["Gear Box"] = kolkata["Gear Box"].str.replace(" ","")
kolkata["Gear Box"]=kolkata["Gear Box"].fillna(tops)
kolkata["Gear Box"]=pd.to_numeric(kolkata["Gear Box"])
print(kolkata["Gear Box"].unique())

[ 5  6  7  4  8  9 10]

In [175]:
kolkata["city"]

0       Bangalore
1       Bangalore
2       Bangalore
3       Bangalore
4       Bangalore
          ...
8326      kolkata
8327      kolkata
8328      kolkata
8329      kolkata
8330      kolkata
Name: city, Length: 8331, dtype: object

In [176]:
#kolkata["bangalore"]=kolkata["city"].apply(lambda x:1 if "Bangalore"in x else 0)
#kolkata["chennai"]=kolkata["city"].apply(lambda x:1 if "chennai" in x else 0)
#kolkata["delhi"]=kolkata["city"].apply(lambda x:1 if "delhi" in x else 0)
#kolkata["hyderabad"]=kolkata["city"].apply(lambda x:1 if "hyderabad"in x else 0)
#kolkata["jaipur"]=kolkata["city"].apply(lambda x:1 if "jaipur" in x else 0)
#kolkata["kolkata"]=kolkata["city"].apply(lambda x:1 if "kolkata"in x else 0)

In [177]:
#kolkata = kolkata.fillna(0)  # Replace NaN values with 0
#kolkata = kolkata.replace([np.inf, -np.inf], 0)  # Replace infinite values with 0

In [178]:
#cit=LabelEncoder()
#kolkata["city"]=cit.fit_transform(kolkata["city"])

In [179]:
#kolkata=kolkata.drop(columns=["Alloy Wheel Size.2"])
#kolkata=kolkata.drop(columns=["Gear Box.1"])
#kolkata=kolkata.drop(columns=["Drive Type.1"])
#kolkata=kolkata.drop(columns=["Front Brake Type.1"])
#kolkata=kolkata.drop(columns=["Rear Brake Type.1"])
#kolkata=kolkata.drop(columns=["Top Speed.1"])
#kolkata=kolkata.drop(columns=["Acceleration.1"])
#kolkata=kolkata.drop(columns=["Turning Radius.1"])

In [180]:
#kolkata=kolkata.drop(columns=["No Door Numbers.2"])

In [181]:
kolkata=kolkata.drop(columns=["trendingText"])

In [182]:
kolkata=kolkata.drop(columns=["owner"])

In [183]:
kolkata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8331 entries, 0 to 8330
Data columns (total 54 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   bt                         8331 non-null   object
 1   km                         8331 non-null   int32
 2   transmission               8331 non-null   object
 3   ownerNo                    8331 non-null   int64
 4   modelYear                  8331 non-null   int64
 5   centralVariantId           8331 non-null   int64
 6   price                      8331 non-null   float64
 7   Registration Year          8331 non-null   int32
 8   Fuel Type                  8331 non-null   object
 9   Seats                      8331 non-null   int32
 10  Kms Driven                 8331 non-null   int32
 11  RTO                        8331 non-null   int32
 12  Ownership                  8331 non-null   int64
 13  Engine Displacement        8331 non-null   int32
 14  Year of Manufacture        8331 non-null   int32
 15  Mileage                    8331 non-null   int32
 16  Wheel Size                 8331 non-null   float64
 17  Engine Type                8331 non-null   int32
 18  No of Cylinder             8295 non-null   float64
 19  Values per Cylinder        8331 non-null   int32
 20  Turbo Charger              8331 non-null   int32
 21  Super Charger              8331 non-null   int64
 22  Length                     8331 non-null   int32
 23  Width                      8331 non-null   int32
 24  Height                     8331 non-null   int32
 25  Wheel Base                 8331 non-null   int32
 26  Front Tread                8331 non-null   int32
 27  Rear Tread                 8331 non-null   int32
 28  Kerb Weight                8331 non-null   int32
 29  No Door Numbers.1          5355 non-null   float64
 30  Gear Box                   8331 non-null   int64
 31  Turning Radius             8331 non-null   int32
 32  Front Brake Type           8331 non-null   int32
 33  Rear Brake Type            8331 non-null   int32
 34  Cargo Volumn               6540 non-null   float64
 35  city                       8331 non-null   object
 36  car_names_encoded          8331 non-null   int32
 37  Model_encoded              8331 non-null   int32
 38  variantName_encoded        8331 non-null   int32
 39  InsuranceValidity          8331 non-null   int32
 40  MaxPower_rpm               8331 non-null   int32
 41  MaxPowerbhp                8331 non-null   float64
 42  TorqueNm                   8331 non-null   float64
 43  ColorEncoded               8331 non-null   int32
 44  Torque_rpm                 8331 non-null   int32
 45  NoOfCylinder               8331 non-null   int32
 46  ValueConfigurationEncoded  8331 non-null   int32
 47  Fuel Suppy System encoded  8331 non-null   int32
 48  SeatingCapacityEncoded     8331 non-null   int64
 49  SteeringTypeEncoded        8331 non-null   int32
 50  TyreTypeEncoded            8331 non-null   int32
 51  NoDoorNumbers              8331 non-null   int32
 52  DriveTypeEncoded           8331 non-null   int32
 53  CargoVolumnlr              8331 non-null   float64
dtypes: float64(8), int32(35), int64(7), object(4)
memory usage: 2.3+ MB

In [184]:
kolkata

,bt,km,transmission,ownerNo,modelYear,centralVariantId,price,Registration Year,Fuel Type,Seats,...,Torque_rpm,NoOfCylinder,ValueConfigurationEncoded,Fuel Suppy System encoded,SeatingCapacityEncoded,SteeringTypeEncoded,TyreTypeEncoded,NoDoorNumbers,DriveTypeEncoded,CargoVolumnlr
0,Hatchback,120000,Manual,3,2015,3979,400000.0,2015,Petrol,5,...,3500,3,3,49,3,5,23,4,10,235.000000
1,SUV,32706,Manual,2,2018,6087,811000.0,2018,Petrol,5,...,4500,3,3,22,3,5,23,4,10,352.000000
2,Hatchback,11949,Manual,1,2018,2983,585000.0,2018,Petrol,5,...,3500,3,3,49,3,5,23,4,10,242.000000
3,Sedan,17794,Manual,1,2014,1867,462000.0,2014,Petrol,5,...,4000,4,3,22,3,5,23,4,11,407.000000
4,SUV,60000,Manual,1,2015,4277,790000.0,2015,Diesel,5,...,1750,4,3,45,3,5,23,4,10,353.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8326,Hatchback,10000,Manual,1,2022,8682,510000.0,2022,Petrol,5,...,3500,3,3,45,2,5,23,5,8,410.000000
8327,Hatchback,120000,Manual,1,2014,3943,180000.0,2014,Petrol,5,...,3500,3,3,49,3,5,23,4,10,8692.819725
8328,Sedan,50000,Automatic,3,2011,4672,550000.0,2011,Petrol,5,...,3733,4,3,53,3,5,23,4,10,8692.819725
8329,Hatchback,40000,Manual,1,2012,4144,140000.0,2012,Petrol,5,...,4000,4,3,45,3,5,23,4,10,8692.819725
8330,SUV,120000,Manual,2,2017,5048,500000.0,2017,Diesel,5,...,1750,4,3,6,3,5,23,4,10,8692.819725

In [185]:
kolkata=kolkata.drop(columns=["No of Cylinder"])

In [186]:
kolkata=kolkata.drop(columns=["No Door Numbers.1"])
kolkata=kolkata.drop(columns=["Cargo Volumn"])

In [187]:
#kolkata=kolkata.drop(columns=['city'])

In [188]:
# Print sorted unique values from the 'modelYear' column
print(sorted(kolkata["modelYear"].unique()))

[1985, 1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]

In [189]:
kolkata["price"]=kolkata["price"].astype(int)

In [190]:
#new=kolkata[['Fuel Type', 'bt','transmission','ownerNo','modelYear','Gear Box','Kms Driven','Mileage','city']]

In [191]:
kolkata["Fuel Type"]

0       Petrol
1       Petrol
2       Petrol
3       Petrol
4       Diesel
         ...
8326    Petrol
8327    Petrol
8328    Petrol
8329    Petrol
8330    Diesel
Name: Fuel Type, Length: 8331, dtype: object

In [192]:
#file="column"
#joblib .dump(dup,file)

In [193]:
new= kolkata[['Fuel Type', 'bt', 'transmission','city']]

In [194]:
column = ['Fuel Type', 'bt', 'transmission', 'city']  # Columns to encode
# Fit and save encoders
for col in column:
    label_encoder = LabelEncoder()
    kolkata[col] = label_encoder.fit_transform(kolkata[col])

In [195]:
columns = ['Fuel Type', 'bt', 'transmission','city']  # Columns to encode
label_encoders = {}

# Fit and save encoders
for col in columns:
    le = LabelEncoder()
    new[col] = le.fit(new[col])
    label_encoders[col] = le  # Save the encoder in the dictionary

# Save the entire dictionary of encoders
joblib.dump(label_encoders, "encoders")

C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\3494877127.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new[col] = le.fit(new[col])
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\3494877127.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new[col] = le.fit(new[col])
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\3494877127.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new[col] = le.fit(new[col])
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\3494877127.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new[col] = le.fit(new[col])

['encoders']

In [196]:
column_label = joblib.load("D:/Desktop/car price prediction/structured files/encoders")

In [197]:
column_label["transmission"].classes_

array(['Automatic', 'Manual'], dtype=object)

In [198]:
#for col in column_label.keys():  # Iterate over each column name
 #   kolkata[col] = column_label[col].transform(data[col])

In [199]:
kolkata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8331 entries, 0 to 8330
Data columns (total 51 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   bt                         8331 non-null   int32
 1   km                         8331 non-null   int32
 2   transmission               8331 non-null   int32
 3   ownerNo                    8331 non-null   int64
 4   modelYear                  8331 non-null   int64
 5   centralVariantId           8331 non-null   int64
 6   price                      8331 non-null   int32
 7   Registration Year          8331 non-null   int32
 8   Fuel Type                  8331 non-null   int32
 9   Seats                      8331 non-null   int32
 10  Kms Driven                 8331 non-null   int32
 11  RTO                        8331 non-null   int32
 12  Ownership                  8331 non-null   int64
 13  Engine Displacement        8331 non-null   int32
 14  Year of Manufacture        8331 non-null   int32
 15  Mileage                    8331 non-null   int32
 16  Wheel Size                 8331 non-null   float64
 17  Engine Type                8331 non-null   int32
 18  Values per Cylinder        8331 non-null   int32
 19  Turbo Charger              8331 non-null   int32
 20  Super Charger              8331 non-null   int64
 21  Length                     8331 non-null   int32
 22  Width                      8331 non-null   int32
 23  Height                     8331 non-null   int32
 24  Wheel Base                 8331 non-null   int32
 25  Front Tread                8331 non-null   int32
 26  Rear Tread                 8331 non-null   int32
 27  Kerb Weight                8331 non-null   int32
 28  Gear Box                   8331 non-null   int64
 29  Turning Radius             8331 non-null   int32
 30  Front Brake Type           8331 non-null   int32
 31  Rear Brake Type            8331 non-null   int32
 32  city                       8331 non-null   int32
 33  car_names_encoded          8331 non-null   int32
 34  Model_encoded              8331 non-null   int32
 35  variantName_encoded        8331 non-null   int32
 36  InsuranceValidity          8331 non-null   int32
 37  MaxPower_rpm               8331 non-null   int32
 38  MaxPowerbhp                8331 non-null   float64
 39  TorqueNm                   8331 non-null   float64
 40  ColorEncoded               8331 non-null   int32
 41  Torque_rpm                 8331 non-null   int32
 42  NoOfCylinder               8331 non-null   int32
 43  ValueConfigurationEncoded  8331 non-null   int32
 44  Fuel Suppy System encoded  8331 non-null   int32
 45  SeatingCapacityEncoded     8331 non-null   int64
 46  SteeringTypeEncoded        8331 non-null   int32
 47  TyreTypeEncoded            8331 non-null   int32
 48  NoDoorNumbers              8331 non-null   int32
 49  DriveTypeEncoded           8331 non-null   int32
 50  CargoVolumnlr              8331 non-null   float64
dtypes: float64(4), int32(40), int64(7)
memory usage: 2.0 MB

In [200]:
import seaborn as sns
import matplotlib.pyplot as plt
#import warnings
#warnings.filterwarnings("ignore")

In [201]:
# data visualization

In [202]:
kolkata.describe()

,bt,km,transmission,ownerNo,modelYear,centralVariantId,price,Registration Year,Fuel Type,Seats,...,Torque_rpm,NoOfCylinder,ValueConfigurationEncoded,Fuel Suppy System encoded,SeatingCapacityEncoded,SteeringTypeEncoded,TyreTypeEncoded,NoDoorNumbers,DriveTypeEncoded,CargoVolumnlr
count,8331.000000,8331.000000,8331.000000,8331.000000,8331.000000,8331.000000,8.331000e+03,8331.000000,8331.000000,8331.000000,...,8331.000000,8331.000000,8331.000000,8331.000000,8331.000000,8331.000000,8331.000000,8331.000000,8331.000000,8.331000e+03
mean,4.392510,55571.235506,0.735206,1.350258,2016.492618,4958.782019,9.196323e+05,2016.613492,3.001080,5.209099,...,3733.581443,3.847197,3.818149,35.564518,2.575801,4.523947,20.661145,4.437523,9.833033,8.692820e+03
std,2.236725,36859.133665,0.441250,0.633967,3.971240,2751.084227,1.389998e+06,3.860059,1.427604,0.678936,...,677.681704,0.941920,1.879296,18.455684,0.863901,1.274177,4.801791,0.510423,1.672127,1.577502e+05
min,0.000000,0.000000,0.000000,0.000000,1985.000000,6.000000,2.016100e+04,2002.000000,0.000000,2.000000,...,1000.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,2.900000e+01
25%,2.000000,30000.000000,0.000000,1.000000,2014.000000,2039.500000,3.685000e+05,2014.000000,1.000000,5.000000,...,3733.000000,4.000000,3.000000,22.000000,2.000000,5.000000,20.000000,4.000000,10.000000,2.850000e+02
50%,6.000000,50000.000000,1.000000,1.000000,2017.000000,5289.000000,5.890000e+05,2017.000000,4.000000,5.000000,...,3733.000000,4.000000,3.000000,45.000000,2.000000,5.000000,23.000000,4.000000,10.000000,4.000000e+02
75%,7.000000,75342.500000,1.000000,2.000000,2019.000000,7122.000000,9.350000e+05,2020.000000,4.000000,5.000000,...,4000.000000,4.000000,3.000000,45.000000,3.000000,5.000000,23.000000,5.000000,10.000000,5.600000e+02
max,8.000000,975000.000000,1.000000,5.000000,2023.000000,11098.000000,4.150000e+07,2023.000000,4.000000,10.000000,...,5000.000000,23.000000,12.000000,76.000000,8.000000,5.000000,29.000000,6.000000,17.000000,3.851405e+06

In [203]:
#num=[]
#cat=[]
#for i in kolkata.columns:
 #   if kolkata[i].nunique()>40:
  #      num.append(i)
   # else:
    #    cat.append(i)
#print(f"num_values:{num}")
#print(f"cat_values:{cat}")

In [204]:
numerical_columns = kolkata.select_dtypes(include=['int','float']).columns
print("numerical columns:", numerical_columns)

numerical columns: Index(['bt', 'km', 'transmission', 'ownerNo', 'modelYear', 'centralVariantId',
       'price', 'Registration Year', 'Fuel Type', 'Seats', 'Kms Driven', 'RTO',
       'Ownership', 'Engine Displacement', 'Year of Manufacture', 'Mileage',
       'Wheel Size', 'Engine Type', 'Values per Cylinder', 'Turbo Charger',
       'Super Charger', 'Length', 'Width', 'Height', 'Wheel Base',
       'Front Tread', 'Rear Tread', 'Kerb Weight', 'Gear Box',
       'Turning Radius', 'Front Brake Type', 'Rear Brake Type', 'city',
       'car_names_encoded', 'Model_encoded', 'variantName_encoded',
       'InsuranceValidity', 'MaxPower_rpm', 'MaxPowerbhp', 'TorqueNm',
       'ColorEncoded', 'Torque_rpm', 'NoOfCylinder',
       'ValueConfigurationEncoded', 'Fuel Suppy System encoded',
       'SeatingCapacityEncoded', 'SteeringTypeEncoded', 'TyreTypeEncoded',
       'NoDoorNumbers', 'DriveTypeEncoded', 'CargoVolumnlr'],
      dtype='object')

In [205]:
kolkata['price'].skew()

10.691297001710442

In [206]:
for cols in ["Engine Type","Seats","Front Brake Type","Rear Brake Type"]:
    plt.figure(figsize=(8, 4))
    sns.displot(x=cols,data=kolkata)
    plt.title(f"Distribution of {cols}")
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.show()

C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\3864961560.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\3864961560.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\3864961560.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\3864961560.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [207]:
for col in numerical_columns:
    plt.figure(figsize=(8, 4))
    sns.boxplot(x=kolkata[col])
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Frequency")
    plt.show()

C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:2: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.
  plt.figure(figsize=(8, 4))
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\1842838950.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [208]:
print(kolkata.dtypes)

bt                             int32
km                             int32
transmission                   int32
ownerNo                        int64
modelYear                      int64
centralVariantId               int64
price                          int32
Registration Year              int32
Fuel Type                      int32
Seats                          int32
Kms Driven                     int32
RTO                            int32
Ownership                      int64
Engine Displacement            int32
Year of Manufacture            int32
Mileage                        int32
Wheel Size                   float64
Engine Type                    int32
Values per Cylinder            int32
Turbo Charger                  int32
Super Charger                  int64
Length                         int32
Width                          int32
Height                         int32
Wheel Base                     int32
Front Tread                    int32
Rear Tread                     int32
Kerb Weight                    int32
Gear Box                       int64
Turning Radius                 int32
Front Brake Type               int32
Rear Brake Type                int32
city                           int32
car_names_encoded              int32
Model_encoded                  int32
variantName_encoded            int32
InsuranceValidity              int32
MaxPower_rpm                   int32
MaxPowerbhp                  float64
TorqueNm                     float64
ColorEncoded                   int32
Torque_rpm                     int32
NoOfCylinder                   int32
ValueConfigurationEncoded      int32
Fuel Suppy System encoded      int32
SeatingCapacityEncoded         int64
SteeringTypeEncoded            int32
TyreTypeEncoded                int32
NoDoorNumbers                  int32
DriveTypeEncoded               int32
CargoVolumnlr                float64
dtype: object

In [209]:
# Iterate through numerical columns
for col in ['km', 'ownerNo', 'modelYear', 'centralVariantId','price',
       'Registration Year','Seats', 'Kms Driven', 'RTO','Gear Box',
       'Ownership', 'Engine Displacement','Mileage',
       'Wheel Size', 'Engine Type', 'Values per Cylinder', 'Turbo Charger',
       'Super Charger', 'Length', 'Width', 'Height', 'Wheel Base', 'Turning Radius', 'InsuranceValidity',
       'MaxPower_rpm', 'MaxPowerbhp', 'TorqueNm', 'Torque_rpm',
       'NoOfCylinder']:
    Q1 = kolkata[col].quantile(0.25)
    Q3 = kolkata[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Clip outliers
    kolkata[col] = kolkata[col].clip(lower=lower_bound, upper=upper_bound)

    # Create a boxplot for the column
    plt.figure(figsize=(8, 6))
    sns.boxplot(x=kolkata[col])  # Plot the clipped column
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.show()

C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\57020291.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [210]:
kolkata.corr()

,bt,km,transmission,ownerNo,modelYear,centralVariantId,price,Registration Year,Fuel Type,Seats,...,Torque_rpm,NoOfCylinder,ValueConfigurationEncoded,Fuel Suppy System encoded,SeatingCapacityEncoded,SteeringTypeEncoded,TyreTypeEncoded,NoDoorNumbers,DriveTypeEncoded,CargoVolumnlr
bt,1.000000,0.058566,-0.265179,-0.034930,0.096249,-0.000429,0.444741,0.095494,-0.296046,NaN,...,0.066527,NaN,0.062820,-0.269885,-0.000303,-0.010291,0.017627,-0.036981,-0.014091,-0.028622
km,0.058566,1.000000,0.145360,0.276506,-0.546241,-0.411798,-0.262313,-0.538599,-0.319738,NaN,...,-0.150687,NaN,0.062343,-0.303157,0.063407,0.084349,0.074677,-0.117138,0.016145,-0.016646
transmission,-0.265179,0.145360,1.000000,0.041293,-0.200857,-0.096895,-0.565983,-0.195587,0.085450,NaN,...,-0.004388,NaN,0.097985,0.087068,-0.018827,-0.013489,-0.023599,0.019282,0.019634,-0.002185
ownerNo,-0.034930,0.276506,0.041293,1.000000,-0.385270,-0.248750,-0.198083,-0.374524,-0.036588,NaN,...,-0.050834,NaN,0.104380,-0.052805,0.054421,0.041261,0.055350,-0.066173,0.014887,-0.013476
modelYear,0.096249,-0.546241,-0.200857,-0.385270,1.000000,0.634588,0.530949,0.975454,0.044507,NaN,...,0.086625,NaN,-0.219076,0.081206,-0.020342,-0.078756,-0.049770,0.053501,0.020246,0.014013
centralVariantId,-0.000429,-0.411798,-0.096895,-0.248750,0.634588,1.000000,0.316760,0.625853,0.127328,NaN,...,0.025477,NaN,-0.273673,0.134636,-0.008193,-0.078332,-0.039741,0.013027,0.003675,0.007640
price,0.444741,-0.262313,-0.565983,-0.198083,0.530949,0.316760,1.000000,0.520079,-0.310974,NaN,...,-0.026623,NaN,-0.222661,-0.256740,0.058343,-0.003427,0.006098,-0.037538,-0.025833,-0.008167
Registration Year,0.095494,-0.538599,-0.195587,-0.374524,0.975454,0.625853,0.520079,1.000000,0.049139,NaN,...,0.084664,NaN,-0.212422,0.084743,-0.018360,-0.075318,-0.043081,0.039787,0.017447,0.014675
Fuel Type,-0.296046,-0.319738,0.085450,-0.036588,0.044507,0.127328,-0.310974,0.049139,1.000000,NaN,...,0.436866,NaN,0.156818,0.761320,-0.045475,-0.036873,-0.000752,0.013025,0.007669,0.010149
Seats,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kms Driven,0.058605,0.999661,0.145651,0.277041,-0.547010,-0.412151,-0.262848,-0.539371,-0.319986,NaN,...,-0.151004,NaN,0.062725,-0.303074,0.063393,0.083894,0.074772,-0.117128,0.016191,-0.016672
RTO,-0.022435,-0.142881,0.093936,-0.065135,0.103844,0.035737,-0.080692,0.101081,0.019103,NaN,...,-0.028171,NaN,-0.022920,0.025492,-0.111609,-0.075418,-0.120388,0.203905,-0.016498,0.013396
Ownership,-0.033673,0.274004,0.039956,0.997660,-0.383128,-0.246505,-0.195093,-0.372057,-0.037581,NaN,...,-0.051298,NaN,0.103568,-0.052447,0.052759,0.041846,0.054637,-0.065697,0.015228,-0.013431
Engine Displacement,0.582194,0.150111,-0.366834,0.031863,-0.011178,-0.108232,0.644485,-0.014039,-0.514656,NaN,...,0.008630,NaN,-0.109234,-0.431026,0.059617,0.015474,0.003508,-0.027984,-0.022882,-0.033856
Year of Manufacture,0.097082,-0.542870,-0.198748,-0.380524,0.990089,0.628442,0.526993,0.993122,0.044863,NaN,...,0.086587,NaN,-0.217170,0.080052,-0.021819,-0.077162,-0.047833,0.049114,0.018811,0.013846
Mileage,-0.319575,-0.021111,0.283134,-0.078366,0.130803,0.130492,-0.393259,0.126082,-0.068030,NaN,...,-0.167927,NaN,-0.066858,-0.057891,-0.035479,-0.008444,0.005610,-0.000850,0.047946,0.012094
Wheel Size,0.368549,-0.168186,-0.407662,-0.150934,0.465566,0.285400,0.711034,0.452100,-0.279103,NaN,...,0.010652,NaN,-0.235019,-0.234281,0.021718,-0.024990,-0.026806,0.025449,-0.005936,-0.013956
Engine Type,0.144926,0.147383,0.032516,0.048172,-0.165866,-0.295952,-0.113173,-0.165604,-0.024592,NaN,...,0.236118,NaN,0.182897,0.033096,0.010575,0.048561,-0.000491,-0.027280,0.019127,-0.027066
Values per Cylinder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Turbo Charger,0.407157,0.174355,-0.235407,-0.027549,0.098992,-0.018467,0.505941,0.091834,-0.701838,NaN,...,-0.427007,NaN,-0.205933,-0.664745,0.055241,0.042035,0.008365,-0.019797,-0.014734,0.006731
Super Charger,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Length,0.430586,0.047238,-0.282942,-0.014044,0.055170,-0.026275,0.462754,0.052618,-0.238283,NaN,...,0.032897,NaN,-0.052421,-0.227697,0.054280,0.018480,0.011936,-0.024472,-0.012573,-0.004510
Width,0.322909,-0.003227,-0.270891,-0.041889,0.129601,0.049921,0.474640,0.126150,-0.242828,NaN,...,0.023542,NaN,-0.113867,-0.246007,0.046946,0.000758,0.004972,-0.008691,-0.023014,0.012919
Height,0.060530,0.018000,-0.041720,-0.004000,0.071566,0.095302,0.207455,0.069081,-0.183032,NaN,...,-0.106084,NaN,-0.089659,-0.120380,0.077178,-0.005109,0.006345,0.051001,-0.037730,0.014574
Wheel Base,0.334441,0.012068,-0.301610,-0.027800,0.085332,0.004757,0.491672,0.083986,-0.243838,NaN,...,-0.006784,NaN,-0.088921,-0.232033,0.052905,0.008077,0.015736,-0.001152,-0.004579,0.010675
Front Tread,0.226592,0.021541,-0.218841,-0.021175,0.089496,0.004589,0.334402,0.090383,-0.161962,NaN,...,0.109319,NaN,-0.076717,-0.184781,0.041249,0.005617,0.022615,-0.037842,-0.000978,0.001028
Rear Tread,0.219946,0.020317,-0.214492,-0.023504,0.095553,0.015471,0.329553,0.095118,-0.163062,NaN,...,0.096151,NaN,-0.094418,-0.191580,0.045693,0.003866,0.022635,-0.034960,-0.000904,0.001137
Kerb Weight,0.037541,-0.061889,0.007617,-0.021069,0.074039,0.083381,0.016304,0.076955,0.029675,NaN,...,0.046964,NaN,-0.031821,0.012599,0.001002,-0.031085,0.004101,-0.007923,0.002760,0.053369
Gear Box,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Turning Radius,0.088318,0.062865,-0.058060,0.000575,0.024863,0.012943,0.091830,0.025393,-0.066363,NaN,...,-0.020497,NaN,-0.012827,-0.050557,-0.081034,-0.172226,-0.081993,0.160902,-0.035078,0.042534
Front Brake Type,0.002541,-0.018622,0.021462,0.023917,-0.058095,-0.042824,-0.022043,-0.056112,0.002454,NaN,...,-0.020257,NaN,0.017489,-0.021441,0.081864,0.103428,0.137473,-0.147052,0.004922,-0.020525
Rear Brake Type,0.005009,0.002259,-0.011583,0.017234,-0.018990,-0.031423,-0.003078,-0.021424,-0.009339,NaN,...,-0.021450,NaN,0.003435,-0.017570,-0.031387,0.024476,0.018519,-0.055835,0.048411,0.001707
city,0.001517,0.034719,0.076904,-0.047068,-0.004715,-0.015556,-0.097329,-0.005387,-0.023619,NaN,...,-0.049426,NaN,0.003959,-0.025954,-0.150034,-0.109810,-0.142583,0.257116,0.008306,-0.000086
car_names_encoded,-0.097912,0.017679,0.051841,-0.035142,0.099037,0.294554,-0.026087,0.098002,-0.030585,NaN,...,-0.244770,NaN,-0.271206,-0.040696,0.023573,0.013074,0.003162,0.004382,0.032226,0.007507
Model_encoded,-0.082515,0.032201,0.035512,-0.024754,0.078853,0.261121,-0.003024,0.077312,-0.049809,NaN,...,-0.240501,NaN,-0.280959,-0.068700,0.024906,0.016816,0.004204,-0.000812,0.034795,0.007188
variantName_encoded,0.018096,-0.103135,0.092842,-0.065424,0.098909,0.205819,-0.039371,0.096268,0.072993,NaN,...,0.023611,NaN,0.082822,0.163816,-0.004019,-0.038978,0.010590,0.014864,-0.004760,-0.010853
InsuranceValidity,-0.003574,0.157387,0.092732,0.138051,-0.125700,-0.083535,-0.121807,-0.125548,-0.046178,NaN,...,-0.081540,NaN,0.020989,-0.027436,0.049264,0.045363,0.052433,-0.089525,-0.009091,-0.000074
MaxPower_rpm,-0.260240,-0.274041,0.084234,-0.033495,0.022154,0.095297,-0.316858,0.023546,0.840775,NaN,...,0.500024,NaN,0.163686,0.736006,-0.058477,-0.050061,0.003638,0.007630,0.012971,0.004420
MaxPowerbhp,0.592836,-0.018351,-0.517333,-0.029316,0.143571,0.018049,0.798524,0.139537,-0.348388,NaN,...,0.039469,NaN,-0.144512,-0.316978,0.034738,-0.001931,-0.005085,-0.015210,-0.026423,-0.016729
TorqueNm,0.490594,0.075760,-0.380111,-0.023863,0.145144,-0.006187,0.708686,0.140542,-0.630738,NaN,...,-0.232420,NaN,-0.225260,-0.568688,0.040981,0.018991,-0.003698,-0.014163,-0.013032,-0.015085
ColorEncoded,-0.036643,0.076044,0.047894,0.035686,-0.037639,-0.013476,-0.053830,-0.035571,-0.005821,NaN,...,0.002623,NaN,-0.010470,-0.007472,0.011642,0.030721,0.022664,-0.037376,0.026892,-0.001313
Torque_rpm,0.066527,-0.150687,-0.004388,-0.050834,0.086625,0.025477,-0.026623,0.084664,0.436866,NaN,...,1.000000,NaN,0.268372,0.419426,-0.024946,-0.052754,-0.002198,-0.022225,0.004994,-0.015976
NoOfCylinder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ValueConfigurationEncoded,0.062820,0.062343,0.097985,0.104380,-0.219076,-0.273673,-0.222661,-0.212422,0.156818,NaN,...,0.268372,NaN,1.000000,0.251542,-0.017721,0.008662,0.036326,-0.001521,-0.030866,-0.002772
Fuel Suppy System encoded,-0.269885,-0.303157,0.087068,-0.052805,0.081206,0.134636,-0.256740,0.084743,0.761320,NaN,...,0.419426,NaN,0.251542,1.000000,-0.029161,-0.041520,-0.002280,0.027531,-0.006589,0.015467
SeatingCapacityEncoded,-0.000303,0.063407,-0.018827,0.054421,-0.020342,-0.008193,0.058343,-0.018360,-0.045475,NaN,...,-0.024946,NaN,-0.017721,-0.029161,1.000000,0.183724,0.239024,-0.045137,-0.023523,-0.015340
SteeringTypeEncoded,-0.010291,0.084349,-0.013489,0.041261,-0.078756,-0.078332,-0.003427,-0.075318,-0.036873,NaN,...,-0.052754,NaN,0.008662,-0.041520,0.183724,1.000000,0.155342,-0.259855,-0.017252,-0.084714
TyreTypeEncoded,0.017627,0.074677,-0.023599,0.055350,-0.049770,-0.039741,0.006098,-0.043081,-0.000752,NaN,...,-0.002198,NaN,0.036326,-0.002280,0.239024,0.155342,1.000000,-0.346921,0.016008,0.001585
NoDoorNumbers,-0.036981,-0.117138,0.019282,-0.066173,0.053501,0.013027,-0.037538,0.039787,0.013025,NaN,...,-0.022225,NaN,-0.001521,0.027531,-0.045137,-0.259855,-0.346921,1.000000,-0.027766,0.026914
DriveTypeEncoded,-0.014091,0.016145,0.019634,0.014887,0.020246,0.003675,-0.025833,0.017447,0.007669,NaN,...,0.004994,NaN,-0.030866,-0.006589,-0.023523,-0.017252,0.016008,-0.027766,1.000000,0.002434
CargoVolumnlr,-0.028622,-0.016646,-0.002185,-0.013476,0.014013,0.007640,-0.008167,0.014675,0.010149,NaN,...,-0.015976,NaN,-0.002772,0.015467,-0.015340,-0.084714,0.001585,0.026914,0.002434,1.000000

In [211]:
cor=kolkata.corr()
plt.figure(figsize=(10, 8))
sns.heatmap(cor, annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()

C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\887210982.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [212]:
#colu=[]
#for i in ['transmission_Automatic','transmission_Manual']:
 #   colu.append(kolkata[i])

#for columN in colu:
 #   print(columN.head())

In [213]:
import joblib

In [214]:
#colu_files="columnshotencode"
#joblib.dump(columN,colu_files)

In [215]:
#colu=[]
#for i in ['ownerNo', 'modelYear','Kms Driven','Mileage']:
 #   colu.append(kolkata[i])
#print(colu)

In [216]:
from sklearn.preprocessing import MinMaxScaler
selected_columns = ['Fuel Type', 'bt','transmission','ownerNo','modelYear','Gear Box','Kms Driven','Mileage','city']
target_column = ['price']
X = kolkata[selected_columns]
y = kolkata[target_column]
ss = MinMaxScaler()
kolkata[X.columns] = ss.fit_transform(X)

In [217]:
kolkata[X.columns]

,Fuel Type,bt,transmission,ownerNo,modelYear,Gear Box,Kms Driven,Mileage,city
0,1.00,0.250,1.0,0.857143,0.515152,0.0,0.836961,0.7500,0.0
1,1.00,0.750,1.0,0.571429,0.696970,0.0,0.227601,0.3750,0.0
2,1.00,0.250,1.0,0.285714,0.696970,0.0,0.082706,0.7500,0.0
3,1.00,0.875,1.0,0.285714,0.454545,0.0,0.123507,0.5000,0.0
4,0.25,0.750,1.0,0.285714,0.515152,0.0,0.418128,0.7500,0.0
...,...,...,...,...,...,...,...,...,...
8326,1.00,0.250,1.0,0.285714,0.939394,0.0,0.069100,0.8750,1.0
8327,1.00,0.250,1.0,0.285714,0.454545,0.0,0.836961,0.6875,1.0
8328,1.00,0.875,0.0,0.857143,0.272727,0.0,0.348322,0.0000,1.0
8329,1.00,0.250,1.0,0.285714,0.333333,0.0,0.278517,0.4375,1.0
8330,0.25,0.750,1.0,0.571429,0.636364,0.0,0.836961,0.5000,1.0

In [218]:
filenames="MinMax.sav"
joblib.dump(ss,filenames)

['MinMax.sav']

In [219]:
scaler=joblib.load("D:/Desktop/car price prediction/structured files/MinMax.sav")

In [220]:
#inputs= ['Fuel Type', 'bt', 'transmission', 'ownerNo', 'modelYear', 'Gear Box', 'Kms Driven', 'Mileage', 'city']

In [221]:
kolkata.columns

Index(['bt', 'km', 'transmission', 'ownerNo', 'modelYear', 'centralVariantId',
       'price', 'Registration Year', 'Fuel Type', 'Seats', 'Kms Driven', 'RTO',
       'Ownership', 'Engine Displacement', 'Year of Manufacture', 'Mileage',
       'Wheel Size', 'Engine Type', 'Values per Cylinder', 'Turbo Charger',
       'Super Charger', 'Length', 'Width', 'Height', 'Wheel Base',
       'Front Tread', 'Rear Tread', 'Kerb Weight', 'Gear Box',
       'Turning Radius', 'Front Brake Type', 'Rear Brake Type', 'city',
       'car_names_encoded', 'Model_encoded', 'variantName_encoded',
       'InsuranceValidity', 'MaxPower_rpm', 'MaxPowerbhp', 'TorqueNm',
       'ColorEncoded', 'Torque_rpm', 'NoOfCylinder',
       'ValueConfigurationEncoded', 'Fuel Suppy System encoded',
       'SeatingCapacityEncoded', 'SteeringTypeEncoded', 'TyreTypeEncoded',
       'NoDoorNumbers', 'DriveTypeEncoded', 'CargoVolumnlr'],
      dtype='object')

In [222]:
# Subset the dataset

In [223]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [224]:
X_train.iloc[0]

Fuel Type            1.00
bt                   3.00
transmission         1.00
ownerNo              1.00
modelYear         2012.00
Gear Box             5.00
Kms Driven      143356.25
Mileage             12.00
city                 5.00
Name: 7069, dtype: float64

In [225]:
X_train, X_test,

(      Fuel Type  bt  transmission  ownerNo  modelYear  Gear Box  Kms Driven  \
 7069          1   3             1      1.0     2012.0         5   143356.25
 1321          4   2             1      1.0     2019.0         5    35000.00
 7351          1   6             0      1.0     2021.0         5    28895.00
 3615          4   6             0      1.0     2020.0         5    19000.00
 7153          4   6             1      1.0     2017.0         5     5151.00
 ...         ...  ..           ...      ...        ...       ...         ...
 5734          1   6             1      2.0     2013.0         5    37421.00
 5191          4   2             1      2.0     2020.0         5    40000.00
 5390          1   2             1      2.0     2018.0         5    79079.00
 860           1   6             0      1.0     2020.0         5    37354.00
 7270          1   7             0      1.0     2012.0         5    52000.00

       Mileage  city
 7069       12     5
 1321       18     0
 7351       18     5
 3615       18     2
 7153       18     5
 ...       ...   ...
 5734       16     3
 5191       20     3
 5390       24     3
 860        17     0
 7270       16     5

 [6664 rows x 9 columns],
       Fuel Type  bt  transmission  ownerNo  modelYear  Gear Box  Kms Driven  \
 7366          4   6             1      1.0     2020.0         5     42970.0
 4051          4   2             1      1.0     2012.0         5     54650.0
 3049          4   7             0      2.0     2018.0         5     21000.0
 4914          4   2             1      1.0     2019.0         5     19348.0
 5353          1   7             1      2.0     2017.0         5     75000.0
 ...         ...  ..           ...      ...        ...       ...         ...
 1097          4   2             1      1.0     2020.0         5     50000.0
 548           4   6             0      1.0     2019.0         5     20000.0
 2925          4   2             1      1.0     2019.0         5     31000.0
 2858          4   2             1      1.0     2014.0         5    120000.0
 5388          4   2             1      1.0     2020.0         5     12740.0

       Mileage  city
 7366       16     5
 4051       18     2
 3049       15     2
 4914       20     3
 5353       21     3
 ...       ...   ...
 1097       21     0
 548        16     0
 2925       18     2
 2858       22     1
 5388       20     3

 [1667 rows x 9 columns])

In [226]:
X_train

,Fuel Type,bt,transmission,ownerNo,modelYear,Gear Box,Kms Driven,Mileage,city
7069,1,3,1,1.0,2012.0,5,143356.25,12,5
1321,4,2,1,1.0,2019.0,5,35000.00,18,0
7351,1,6,0,1.0,2021.0,5,28895.00,18,5
3615,4,6,0,1.0,2020.0,5,19000.00,18,2
7153,4,6,1,1.0,2017.0,5,5151.00,18,5
...,...,...,...,...,...,...,...,...,...
5734,1,6,1,2.0,2013.0,5,37421.00,16,3
5191,4,2,1,2.0,2020.0,5,40000.00,20,3
5390,1,2,1,2.0,2018.0,5,79079.00,24,3
860,1,6,0,1.0,2020.0,5,37354.00,17,0
7270,1,7,0,1.0,2012.0,5,52000.00,16,5

In [227]:
from sklearn.linear_model import LinearRegression
model_lin = LinearRegression()

model_lin.fit(X_train, y_train)

LinearRegression()

In [228]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [229]:
from sklearn.ensemble import RandomForestRegressor

model_forest = RandomForestRegressor(random_state=42)

# Fit the model to the training data
model_forest.fit(X_train, y_train)

c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(random_state=42)

In [230]:
y_pred = model_forest.predict(X_test)

# Mean Absolute Error (MAE)
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error: {mae}")

# Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# Root Mean Squared Error (RMSE)
rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f"Root Mean Squared Error: {rmse}")

# R-squared (R²)
r2 = r2_score(y_test, y_pred)
print(f"R-squared: {r2}")

Mean Absolute Error: 118286.64094406248
Mean Squared Error: 34350416851.594494
Root Mean Squared Error: 185338.65449925576
R-squared: 0.8575922277816979

c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(

In [231]:
scaler = joblib.load("D:/Desktop/car price prediction/structured files/MinMax.sav")

In [261]:
new_data =[[ 1,7,0,1,2016,4,20000, 16, 4]]
new_data_scaled = scaler.transform(new_data)
predd = model_forest.predict(new_data_scaled)
predd

[[ 0.25        0.875       0.          0.28571429  0.57575758 -1.
   0.1389059   0.3125      0.8       ]]

c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([1102015.])

In [ ]:

print(X_train.describe())

         Fuel Type           bt  transmission      ownerNo    modelYear  \
count  6664.000000  6664.000000   6664.000000  6664.000000  6664.000000
mean      2.989196     4.397959      0.737245     1.346489  2016.504052
std       1.432310     2.239810      0.440164     0.602655     3.809323
min       0.000000     0.000000      0.000000     0.000000  2006.500000
25%       1.000000     2.000000      0.000000     1.000000  2014.000000
50%       4.000000     6.000000      1.000000     1.000000  2017.000000
75%       4.000000     7.000000      1.000000     2.000000  2019.000000
max       4.000000     8.000000      1.000000     3.500000  2023.000000

       Gear Box     Kms Driven      Mileage         city
count    6664.0    6664.000000  6664.000000  6664.000000
mean        5.0   55286.904112    18.737545     2.429172
std         0.0   33127.511799     3.461023     1.704078
min         5.0     101.000000    11.000000     0.000000
25%         5.0   30000.000000    17.000000     1.000000
50%         5.0   50000.000000    19.000000     2.000000
75%         5.0   76000.000000    21.000000     4.000000
max         5.0  143356.250000    27.000000     5.000000

In [234]:
import matplotlib.pyplot as plt
plt.hist(y_train, bins=50)
plt.title('Price Distribution')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.show()

C:\Users\Welcome\AppData\Local\Temp\ipykernel_11268\394277002.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [235]:
filename="predicted_price.sav"
joblib.dump(model_forest,filename)

['predicted_price.sav']

In [236]:
load_saved=joblib.load("D:/Desktop/car price prediction/structured files/predicted_price.sav")

In [237]:
min_loaded=joblib.load("D:/Desktop/car price prediction/structured files/MinMax.sav")
column_label=joblib.load("D:/Desktop/car price prediction/structured files/columnsLabel")

load_saved=joblib.load("D:/Desktop/car price prediction/structured files/predicted_price.sav")

In [238]:
min_loaded
column_label
#column
#load_saved

LabelEncoder()

In [239]:
input=[
"Diesel",
"MUV",
"Manual",
4,
2010,
5,
10000,
15,
"Delhi"
]

In [240]:
column=joblib.load("D:/Desktop/car price prediction/structured files/column")

FileNotFoundError: [Errno 2] No such file or directory: 'D:/Desktop/car price prediction/structured files/column'